/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package drg.moh.service.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the DashboardChiPhiThanhPhan service. Represents a row in the &quot;rp_dashboard_chiphi_thanhphan&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>drg.moh.service.model.impl.DashboardChiPhiThanhPhanModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>drg.moh.service.model.impl.DashboardChiPhiThanhPhanImpl</code>.
 * </p>
 *
 * @author SON
 * @see DashboardChiPhiThanhPhan
 * @generated
 */
@ProviderType
public interface DashboardChiPhiThanhPhanModel
	extends BaseModel<DashboardChiPhiThanhPhan> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a dashboard chi phi thanh phan model instance should use the {@link DashboardChiPhiThanhPhan} interface instead.
	 */

	/**
	 * Returns the primary key of this dashboard chi phi thanh phan.
	 *
	 * @return the primary key of this dashboard chi phi thanh phan
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this dashboard chi phi thanh phan.
	 *
	 * @param primaryKey the primary key of this dashboard chi phi thanh phan
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this dashboard chi phi thanh phan.
	 *
	 * @return the ID of this dashboard chi phi thanh phan
	 */
	public long getId();

	/**
	 * Sets the ID of this dashboard chi phi thanh phan.
	 *
	 * @param id the ID of this dashboard chi phi thanh phan
	 */
	public void setId(long id);

	/**
	 * Returns the muc bc of this dashboard chi phi thanh phan.
	 *
	 * @return the muc bc of this dashboard chi phi thanh phan
	 */
	public int getMucBc();

	/**
	 * Sets the muc bc of this dashboard chi phi thanh phan.
	 *
	 * @param mucBc the muc bc of this dashboard chi phi thanh phan
	 */
	public void setMucBc(int mucBc);

	/**
	 * Returns the nam of this dashboard chi phi thanh phan.
	 *
	 * @return the nam of this dashboard chi phi thanh phan
	 */
	public int getNam();

	/**
	 * Sets the nam of this dashboard chi phi thanh phan.
	 *
	 * @param nam the nam of this dashboard chi phi thanh phan
	 */
	public void setNam(int nam);

	/**
	 * Returns the org ID of this dashboard chi phi thanh phan.
	 *
	 * @return the org ID of this dashboard chi phi thanh phan
	 */
	public long getOrgId();

	/**
	 * Sets the org ID of this dashboard chi phi thanh phan.
	 *
	 * @param orgId the org ID of this dashboard chi phi thanh phan
	 */
	public void setOrgId(long orgId);

	/**
	 * Returns the org name of this dashboard chi phi thanh phan.
	 *
	 * @return the org name of this dashboard chi phi thanh phan
	 */
	@AutoEscape
	public String getOrgName();

	/**
	 * Sets the org name of this dashboard chi phi thanh phan.
	 *
	 * @param orgName the org name of this dashboard chi phi thanh phan
	 */
	public void setOrgName(String orgName);

	/**
	 * Returns the phi of this dashboard chi phi thanh phan.
	 *
	 * @return the phi of this dashboard chi phi thanh phan
	 */
	public double getPhi();

	/**
	 * Sets the phi of this dashboard chi phi thanh phan.
	 *
	 * @param phi the phi of this dashboard chi phi thanh phan
	 */
	public void setPhi(double phi);

	/**
	 * Returns the dinh suat of this dashboard chi phi thanh phan.
	 *
	 * @return the dinh suat of this dashboard chi phi thanh phan
	 */
	public double getDinhSuat();

	/**
	 * Sets the dinh suat of this dashboard chi phi thanh phan.
	 *
	 * @param dinhSuat the dinh suat of this dashboard chi phi thanh phan
	 */
	public void setDinhSuat(double dinhSuat);

	/**
	 * Returns the drg of this dashboard chi phi thanh phan.
	 *
	 * @return the drg of this dashboard chi phi thanh phan
	 */
	public double getDrg();

	/**
	 * Sets the drg of this dashboard chi phi thanh phan.
	 *
	 * @param drg the drg of this dashboard chi phi thanh phan
	 */
	public void setDrg(double drg);

}