/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package drg.moh.service.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the DashboardChiPhiHoatDong service. Represents a row in the &quot;rp_dashboard_chiphi_hoatdong&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>drg.moh.service.model.impl.DashboardChiPhiHoatDongModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>drg.moh.service.model.impl.DashboardChiPhiHoatDongImpl</code>.
 * </p>
 *
 * @author SON
 * @see DashboardChiPhiHoatDong
 * @generated
 */
@ProviderType
public interface DashboardChiPhiHoatDongModel
	extends BaseModel<DashboardChiPhiHoatDong> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a dashboard chi phi hoat dong model instance should use the {@link DashboardChiPhiHoatDong} interface instead.
	 */

	/**
	 * Returns the primary key of this dashboard chi phi hoat dong.
	 *
	 * @return the primary key of this dashboard chi phi hoat dong
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this dashboard chi phi hoat dong.
	 *
	 * @param primaryKey the primary key of this dashboard chi phi hoat dong
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this dashboard chi phi hoat dong.
	 *
	 * @return the ID of this dashboard chi phi hoat dong
	 */
	public long getId();

	/**
	 * Sets the ID of this dashboard chi phi hoat dong.
	 *
	 * @param id the ID of this dashboard chi phi hoat dong
	 */
	public void setId(long id);

	/**
	 * Returns the muc bc of this dashboard chi phi hoat dong.
	 *
	 * @return the muc bc of this dashboard chi phi hoat dong
	 */
	public int getMucBc();

	/**
	 * Sets the muc bc of this dashboard chi phi hoat dong.
	 *
	 * @param mucBc the muc bc of this dashboard chi phi hoat dong
	 */
	public void setMucBc(int mucBc);

	/**
	 * Returns the nam of this dashboard chi phi hoat dong.
	 *
	 * @return the nam of this dashboard chi phi hoat dong
	 */
	public int getNam();

	/**
	 * Sets the nam of this dashboard chi phi hoat dong.
	 *
	 * @param nam the nam of this dashboard chi phi hoat dong
	 */
	public void setNam(int nam);

	/**
	 * Returns the org ID of this dashboard chi phi hoat dong.
	 *
	 * @return the org ID of this dashboard chi phi hoat dong
	 */
	public long getOrgId();

	/**
	 * Sets the org ID of this dashboard chi phi hoat dong.
	 *
	 * @param orgId the org ID of this dashboard chi phi hoat dong
	 */
	public void setOrgId(long orgId);

	/**
	 * Returns the org name of this dashboard chi phi hoat dong.
	 *
	 * @return the org name of this dashboard chi phi hoat dong
	 */
	@AutoEscape
	public String getOrgName();

	/**
	 * Sets the org name of this dashboard chi phi hoat dong.
	 *
	 * @param orgName the org name of this dashboard chi phi hoat dong
	 */
	public void setOrgName(String orgName);

	/**
	 * Returns the thanh phan ID of this dashboard chi phi hoat dong.
	 *
	 * @return the thanh phan ID of this dashboard chi phi hoat dong
	 */
	@AutoEscape
	public String getThanhPhanId();

	/**
	 * Sets the thanh phan ID of this dashboard chi phi hoat dong.
	 *
	 * @param thanhPhanId the thanh phan ID of this dashboard chi phi hoat dong
	 */
	public void setThanhPhanId(String thanhPhanId);

	/**
	 * Returns the thanh phan ma of this dashboard chi phi hoat dong.
	 *
	 * @return the thanh phan ma of this dashboard chi phi hoat dong
	 */
	@AutoEscape
	public String getThanhPhanMa();

	/**
	 * Sets the thanh phan ma of this dashboard chi phi hoat dong.
	 *
	 * @param thanhPhanMa the thanh phan ma of this dashboard chi phi hoat dong
	 */
	public void setThanhPhanMa(String thanhPhanMa);

	/**
	 * Returns the thanh phan ten of this dashboard chi phi hoat dong.
	 *
	 * @return the thanh phan ten of this dashboard chi phi hoat dong
	 */
	@AutoEscape
	public String getThanhPhanTen();

	/**
	 * Sets the thanh phan ten of this dashboard chi phi hoat dong.
	 *
	 * @param thanhPhanTen the thanh phan ten of this dashboard chi phi hoat dong
	 */
	public void setThanhPhanTen(String thanhPhanTen);

	/**
	 * Returns the drg phi dv of this dashboard chi phi hoat dong.
	 *
	 * @return the drg phi dv of this dashboard chi phi hoat dong
	 */
	public double getDrgPhiDv();

	/**
	 * Sets the drg phi dv of this dashboard chi phi hoat dong.
	 *
	 * @param drgPhiDv the drg phi dv of this dashboard chi phi hoat dong
	 */
	public void setDrgPhiDv(double drgPhiDv);

	/**
	 * Returns the drg dinh suat of this dashboard chi phi hoat dong.
	 *
	 * @return the drg dinh suat of this dashboard chi phi hoat dong
	 */
	public double getDrgDinhSuat();

	/**
	 * Sets the drg dinh suat of this dashboard chi phi hoat dong.
	 *
	 * @param drgDinhSuat the drg dinh suat of this dashboard chi phi hoat dong
	 */
	public void setDrgDinhSuat(double drgDinhSuat);

	/**
	 * Returns the drg values of this dashboard chi phi hoat dong.
	 *
	 * @return the drg values of this dashboard chi phi hoat dong
	 */
	public double getDrgValues();

	/**
	 * Sets the drg values of this dashboard chi phi hoat dong.
	 *
	 * @param drgValues the drg values of this dashboard chi phi hoat dong
	 */
	public void setDrgValues(double drgValues);

}