/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package drg.moh.service.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the DashboardBaoHiem service. Represents a row in the &quot;rp_dashboard_baohiem&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>drg.moh.service.model.impl.DashboardBaoHiemModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>drg.moh.service.model.impl.DashboardBaoHiemImpl</code>.
 * </p>
 *
 * @author SON
 * @see DashboardBaoHiem
 * @generated
 */
@ProviderType
public interface DashboardBaoHiemModel extends BaseModel<DashboardBaoHiem> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a dashboard bao hiem model instance should use the {@link DashboardBaoHiem} interface instead.
	 */

	/**
	 * Returns the primary key of this dashboard bao hiem.
	 *
	 * @return the primary key of this dashboard bao hiem
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this dashboard bao hiem.
	 *
	 * @param primaryKey the primary key of this dashboard bao hiem
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this dashboard bao hiem.
	 *
	 * @return the ID of this dashboard bao hiem
	 */
	public long getId();

	/**
	 * Sets the ID of this dashboard bao hiem.
	 *
	 * @param id the ID of this dashboard bao hiem
	 */
	public void setId(long id);

	/**
	 * Returns the muc bc of this dashboard bao hiem.
	 *
	 * @return the muc bc of this dashboard bao hiem
	 */
	public int getMucBc();

	/**
	 * Sets the muc bc of this dashboard bao hiem.
	 *
	 * @param mucBc the muc bc of this dashboard bao hiem
	 */
	public void setMucBc(int mucBc);

	/**
	 * Returns the nam of this dashboard bao hiem.
	 *
	 * @return the nam of this dashboard bao hiem
	 */
	public int getNam();

	/**
	 * Sets the nam of this dashboard bao hiem.
	 *
	 * @param nam the nam of this dashboard bao hiem
	 */
	public void setNam(int nam);

	/**
	 * Returns the thang of this dashboard bao hiem.
	 *
	 * @return the thang of this dashboard bao hiem
	 */
	public int getThang();

	/**
	 * Sets the thang of this dashboard bao hiem.
	 *
	 * @param thang the thang of this dashboard bao hiem
	 */
	public void setThang(int thang);

	/**
	 * Returns the org ID of this dashboard bao hiem.
	 *
	 * @return the org ID of this dashboard bao hiem
	 */
	public long getOrgId();

	/**
	 * Sets the org ID of this dashboard bao hiem.
	 *
	 * @param orgId the org ID of this dashboard bao hiem
	 */
	public void setOrgId(long orgId);

	/**
	 * Returns the org name of this dashboard bao hiem.
	 *
	 * @return the org name of this dashboard bao hiem
	 */
	@AutoEscape
	public String getOrgName();

	/**
	 * Sets the org name of this dashboard bao hiem.
	 *
	 * @param orgName the org name of this dashboard bao hiem
	 */
	public void setOrgName(String orgName);

	/**
	 * Returns the drg ma of this dashboard bao hiem.
	 *
	 * @return the drg ma of this dashboard bao hiem
	 */
	@AutoEscape
	public String getDrgMa();

	/**
	 * Sets the drg ma of this dashboard bao hiem.
	 *
	 * @param drgMa the drg ma of this dashboard bao hiem
	 */
	public void setDrgMa(String drgMa);

	/**
	 * Returns the drg ten of this dashboard bao hiem.
	 *
	 * @return the drg ten of this dashboard bao hiem
	 */
	@AutoEscape
	public String getDrgTen();

	/**
	 * Sets the drg ten of this dashboard bao hiem.
	 *
	 * @param drgTen the drg ten of this dashboard bao hiem
	 */
	public void setDrgTen(String drgTen);

	/**
	 * Returns the drg value of this dashboard bao hiem.
	 *
	 * @return the drg value of this dashboard bao hiem
	 */
	public double getDrgValue();

	/**
	 * Sets the drg value of this dashboard bao hiem.
	 *
	 * @param drgValue the drg value of this dashboard bao hiem
	 */
	public void setDrgValue(double drgValue);

	/**
	 * Returns the drg up of this dashboard bao hiem.
	 *
	 * @return the drg up of this dashboard bao hiem
	 */
	public double getDrgUp();

	/**
	 * Sets the drg up of this dashboard bao hiem.
	 *
	 * @param drgUp the drg up of this dashboard bao hiem
	 */
	public void setDrgUp(double drgUp);

	/**
	 * Returns the drg down of this dashboard bao hiem.
	 *
	 * @return the drg down of this dashboard bao hiem
	 */
	public double getDrgDown();

	/**
	 * Sets the drg down of this dashboard bao hiem.
	 *
	 * @param drgDown the drg down of this dashboard bao hiem
	 */
	public void setDrgDown(double drgDown);

}