/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package drg.moh.service.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the RpDashboardCmi2 service. Represents a row in the &quot;func_dashboard_cmi_2&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>drg.moh.service.model.impl.RpDashboardCmi2ModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>drg.moh.service.model.impl.RpDashboardCmi2Impl</code>.
 * </p>
 *
 * @author SON
 * @see RpDashboardCmi2
 * @generated
 */
@ProviderType
public interface RpDashboardCmi2Model extends BaseModel<RpDashboardCmi2> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a rp dashboard cmi2 model instance should use the {@link RpDashboardCmi2} interface instead.
	 */

	/**
	 * Returns the primary key of this rp dashboard cmi2.
	 *
	 * @return the primary key of this rp dashboard cmi2
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this rp dashboard cmi2.
	 *
	 * @param primaryKey the primary key of this rp dashboard cmi2
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this rp dashboard cmi2.
	 *
	 * @return the ID of this rp dashboard cmi2
	 */
	public long getId();

	/**
	 * Sets the ID of this rp dashboard cmi2.
	 *
	 * @param id the ID of this rp dashboard cmi2
	 */
	public void setId(long id);

	/**
	 * Returns the cmi ten tuyen of this rp dashboard cmi2.
	 *
	 * @return the cmi ten tuyen of this rp dashboard cmi2
	 */
	@AutoEscape
	public String getCmiTenTuyen();

	/**
	 * Sets the cmi ten tuyen of this rp dashboard cmi2.
	 *
	 * @param cmiTenTuyen the cmi ten tuyen of this rp dashboard cmi2
	 */
	public void setCmiTenTuyen(String cmiTenTuyen);

	/**
	 * Returns the cmi trung binh of this rp dashboard cmi2.
	 *
	 * @return the cmi trung binh of this rp dashboard cmi2
	 */
	public double getCmiTrungBinh();

	/**
	 * Sets the cmi trung binh of this rp dashboard cmi2.
	 *
	 * @param cmiTrungBinh the cmi trung binh of this rp dashboard cmi2
	 */
	public void setCmiTrungBinh(double cmiTrungBinh);

	/**
	 * Returns the cmi trung max of this rp dashboard cmi2.
	 *
	 * @return the cmi trung max of this rp dashboard cmi2
	 */
	public double getCmiTrungMax();

	/**
	 * Sets the cmi trung max of this rp dashboard cmi2.
	 *
	 * @param cmiTrungMax the cmi trung max of this rp dashboard cmi2
	 */
	public void setCmiTrungMax(double cmiTrungMax);

	/**
	 * Returns the cmi trung min of this rp dashboard cmi2.
	 *
	 * @return the cmi trung min of this rp dashboard cmi2
	 */
	public double getCmiTrungMin();

	/**
	 * Sets the cmi trung min of this rp dashboard cmi2.
	 *
	 * @param cmiTrungMin the cmi trung min of this rp dashboard cmi2
	 */
	public void setCmiTrungMin(double cmiTrungMin);

}