/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package drg.moh.service.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the RpDashboardDstcChiTiet service. Represents a row in the &quot;rp_dashboard_dstc_chitiet&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>drg.moh.service.model.impl.RpDashboardDstcChiTietModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>drg.moh.service.model.impl.RpDashboardDstcChiTietImpl</code>.
 * </p>
 *
 * @author SON
 * @see RpDashboardDstcChiTiet
 * @generated
 */
@ProviderType
public interface RpDashboardDstcChiTietModel
	extends BaseModel<RpDashboardDstcChiTiet> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a rp dashboard dstc chi tiet model instance should use the {@link RpDashboardDstcChiTiet} interface instead.
	 */

	/**
	 * Returns the primary key of this rp dashboard dstc chi tiet.
	 *
	 * @return the primary key of this rp dashboard dstc chi tiet
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this rp dashboard dstc chi tiet.
	 *
	 * @param primaryKey the primary key of this rp dashboard dstc chi tiet
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the ID of this rp dashboard dstc chi tiet.
	 *
	 * @return the ID of this rp dashboard dstc chi tiet
	 */
	@AutoEscape
	public String getId();

	/**
	 * Sets the ID of this rp dashboard dstc chi tiet.
	 *
	 * @param id the ID of this rp dashboard dstc chi tiet
	 */
	public void setId(String id);

	/**
	 * Returns the ten tinh of this rp dashboard dstc chi tiet.
	 *
	 * @return the ten tinh of this rp dashboard dstc chi tiet
	 */
	@AutoEscape
	public String getTenTinh();

	/**
	 * Sets the ten tinh of this rp dashboard dstc chi tiet.
	 *
	 * @param tenTinh the ten tinh of this rp dashboard dstc chi tiet
	 */
	public void setTenTinh(String tenTinh);

	/**
	 * Returns the dinh suat of this rp dashboard dstc chi tiet.
	 *
	 * @return the dinh suat of this rp dashboard dstc chi tiet
	 */
	public int getDinhSuat();

	/**
	 * Sets the dinh suat of this rp dashboard dstc chi tiet.
	 *
	 * @param dinhSuat the dinh suat of this rp dashboard dstc chi tiet
	 */
	public void setDinhSuat(int dinhSuat);

}