/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package drg.moh.service.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the RpDashboardTrungBinh service. Represents a row in the &quot;DRG_RpDashboardTrungBinh&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>drg.moh.service.model.impl.RpDashboardTrungBinhModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>drg.moh.service.model.impl.RpDashboardTrungBinhImpl</code>.
 * </p>
 *
 * @author SON
 * @see RpDashboardTrungBinh
 * @generated
 */
@ProviderType
public interface RpDashboardTrungBinhModel
	extends BaseModel<RpDashboardTrungBinh> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a rp dashboard trung binh model instance should use the {@link RpDashboardTrungBinh} interface instead.
	 */

	/**
	 * Returns the primary key of this rp dashboard trung binh.
	 *
	 * @return the primary key of this rp dashboard trung binh
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this rp dashboard trung binh.
	 *
	 * @param primaryKey the primary key of this rp dashboard trung binh
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the data of this rp dashboard trung binh.
	 *
	 * @return the data of this rp dashboard trung binh
	 */
	@AutoEscape
	public String getData();

	/**
	 * Sets the data of this rp dashboard trung binh.
	 *
	 * @param data the data of this rp dashboard trung binh
	 */
	public void setData(String data);

}