/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package drg.moh.service.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the RpDashboardDRG service. Represents a row in the &quot;rp_dashboard_drg&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>drg.moh.service.model.impl.RpDashboardDRGModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>drg.moh.service.model.impl.RpDashboardDRGImpl</code>.
 * </p>
 *
 * @author SON
 * @see RpDashboardDRG
 * @generated
 */
@ProviderType
public interface RpDashboardDRGModel extends BaseModel<RpDashboardDRG> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a rp dashboard drg model instance should use the {@link RpDashboardDRG} interface instead.
	 */

	/**
	 * Returns the primary key of this rp dashboard drg.
	 *
	 * @return the primary key of this rp dashboard drg
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this rp dashboard drg.
	 *
	 * @param primaryKey the primary key of this rp dashboard drg
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this rp dashboard drg.
	 *
	 * @return the ID of this rp dashboard drg
	 */
	public long getId();

	/**
	 * Sets the ID of this rp dashboard drg.
	 *
	 * @param id the ID of this rp dashboard drg
	 */
	public void setId(long id);

	/**
	 * Returns the drg of this rp dashboard drg.
	 *
	 * @return the drg of this rp dashboard drg
	 */
	@AutoEscape
	public String getDrg();

	/**
	 * Sets the drg of this rp dashboard drg.
	 *
	 * @param drg the drg of this rp dashboard drg
	 */
	public void setDrg(String drg);

	/**
	 * Returns the thang of this rp dashboard drg.
	 *
	 * @return the thang of this rp dashboard drg
	 */
	@AutoEscape
	public String getThang();

	/**
	 * Sets the thang of this rp dashboard drg.
	 *
	 * @param thang the thang of this rp dashboard drg
	 */
	public void setThang(String thang);

	/**
	 * Returns the value of this rp dashboard drg.
	 *
	 * @return the value of this rp dashboard drg
	 */
	public double getValue();

	/**
	 * Sets the value of this rp dashboard drg.
	 *
	 * @param value the value of this rp dashboard drg
	 */
	public void setValue(double value);

}