/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package drg.moh.service.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the RpDashboardCmi service. Represents a row in the &quot;rp_dashboard_cmi&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>drg.moh.service.model.impl.RpDashboardCmiModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>drg.moh.service.model.impl.RpDashboardCmiImpl</code>.
 * </p>
 *
 * @author SON
 * @see RpDashboardCmi
 * @generated
 */
@ProviderType
public interface RpDashboardCmiModel extends BaseModel<RpDashboardCmi> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a rp dashboard cmi model instance should use the {@link RpDashboardCmi} interface instead.
	 */

	/**
	 * Returns the primary key of this rp dashboard cmi.
	 *
	 * @return the primary key of this rp dashboard cmi
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this rp dashboard cmi.
	 *
	 * @param primaryKey the primary key of this rp dashboard cmi
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this rp dashboard cmi.
	 *
	 * @return the ID of this rp dashboard cmi
	 */
	public long getId();

	/**
	 * Sets the ID of this rp dashboard cmi.
	 *
	 * @param id the ID of this rp dashboard cmi
	 */
	public void setId(long id);

	/**
	 * Returns the cmi toan quoc of this rp dashboard cmi.
	 *
	 * @return the cmi toan quoc of this rp dashboard cmi
	 */
	public double getCmiToanQuoc();

	/**
	 * Sets the cmi toan quoc of this rp dashboard cmi.
	 *
	 * @param cmiToanQuoc the cmi toan quoc of this rp dashboard cmi
	 */
	public void setCmiToanQuoc(double cmiToanQuoc);

	/**
	 * Returns the cmi tinh of this rp dashboard cmi.
	 *
	 * @return the cmi tinh of this rp dashboard cmi
	 */
	public double getCmiTinh();

	/**
	 * Sets the cmi tinh of this rp dashboard cmi.
	 *
	 * @param cmiTinh the cmi tinh of this rp dashboard cmi
	 */
	public void setCmiTinh(double cmiTinh);

	/**
	 * Returns the cmi tuyen of this rp dashboard cmi.
	 *
	 * @return the cmi tuyen of this rp dashboard cmi
	 */
	@AutoEscape
	public String getCmiTuyen();

	/**
	 * Sets the cmi tuyen of this rp dashboard cmi.
	 *
	 * @param cmiTuyen the cmi tuyen of this rp dashboard cmi
	 */
	public void setCmiTuyen(String cmiTuyen);

	/**
	 * Returns the cmi trung binh of this rp dashboard cmi.
	 *
	 * @return the cmi trung binh of this rp dashboard cmi
	 */
	public double getCmiTrungBinh();

	/**
	 * Sets the cmi trung binh of this rp dashboard cmi.
	 *
	 * @param cmiTrungBinh the cmi trung binh of this rp dashboard cmi
	 */
	public void setCmiTrungBinh(double cmiTrungBinh);

	/**
	 * Returns the cmi trung max of this rp dashboard cmi.
	 *
	 * @return the cmi trung max of this rp dashboard cmi
	 */
	public double getCmiTrungMax();

	/**
	 * Sets the cmi trung max of this rp dashboard cmi.
	 *
	 * @param cmiTrungMax the cmi trung max of this rp dashboard cmi
	 */
	public void setCmiTrungMax(double cmiTrungMax);

	/**
	 * Returns the cmi trung min of this rp dashboard cmi.
	 *
	 * @return the cmi trung min of this rp dashboard cmi
	 */
	public double getCmiTrungMin();

	/**
	 * Sets the cmi trung min of this rp dashboard cmi.
	 *
	 * @param cmiTrungMin the cmi trung min of this rp dashboard cmi
	 */
	public void setCmiTrungMin(double cmiTrungMin);

	/**
	 * Returns the cmi co so of this rp dashboard cmi.
	 *
	 * @return the cmi co so of this rp dashboard cmi
	 */
	public double getCmiCoSo();

	/**
	 * Sets the cmi co so of this rp dashboard cmi.
	 *
	 * @param cmiCoSo the cmi co so of this rp dashboard cmi
	 */
	public void setCmiCoSo(double cmiCoSo);

}