/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package drg.moh.service.model;

import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the RpDashboardChiPhiBinhQuan service. Represents a row in the &quot;rp_dashboard_chiphibinhquan&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>drg.moh.service.model.impl.RpDashboardChiPhiBinhQuanModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>drg.moh.service.model.impl.RpDashboardChiPhiBinhQuanImpl</code>.
 * </p>
 *
 * @author SON
 * @see RpDashboardChiPhiBinhQuan
 * @generated
 */
@ProviderType
public interface RpDashboardChiPhiBinhQuanModel
	extends BaseModel<RpDashboardChiPhiBinhQuan> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a rp dashboard chi phi binh quan model instance should use the {@link RpDashboardChiPhiBinhQuan} interface instead.
	 */

	/**
	 * Returns the primary key of this rp dashboard chi phi binh quan.
	 *
	 * @return the primary key of this rp dashboard chi phi binh quan
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this rp dashboard chi phi binh quan.
	 *
	 * @param primaryKey the primary key of this rp dashboard chi phi binh quan
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this rp dashboard chi phi binh quan.
	 *
	 * @return the ID of this rp dashboard chi phi binh quan
	 */
	public long getId();

	/**
	 * Sets the ID of this rp dashboard chi phi binh quan.
	 *
	 * @param id the ID of this rp dashboard chi phi binh quan
	 */
	public void setId(long id);

	/**
	 * Returns the chi phi of this rp dashboard chi phi binh quan.
	 *
	 * @return the chi phi of this rp dashboard chi phi binh quan
	 */
	public double getChiPhi();

	/**
	 * Sets the chi phi of this rp dashboard chi phi binh quan.
	 *
	 * @param chiPhi the chi phi of this rp dashboard chi phi binh quan
	 */
	public void setChiPhi(double chiPhi);

	/**
	 * Returns the binh quan of this rp dashboard chi phi binh quan.
	 *
	 * @return the binh quan of this rp dashboard chi phi binh quan
	 */
	public double getBinhQuan();

	/**
	 * Sets the binh quan of this rp dashboard chi phi binh quan.
	 *
	 * @param binhQuan the binh quan of this rp dashboard chi phi binh quan
	 */
	public void setBinhQuan(double binhQuan);

}