/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package drg.moh.service.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the ViewDanhSachBenhAn service. Represents a row in the &quot;view_danhsach_hsba&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>drg.moh.service.model.impl.ViewDanhSachBenhAnModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>drg.moh.service.model.impl.ViewDanhSachBenhAnImpl</code>.
 * </p>
 *
 * @author SON
 * @see ViewDanhSachBenhAn
 * @generated
 */
@ProviderType
public interface ViewDanhSachBenhAnModel extends BaseModel<ViewDanhSachBenhAn> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a view danh sach benh an model instance should use the {@link ViewDanhSachBenhAn} interface instead.
	 */

	/**
	 * Returns the primary key of this view danh sach benh an.
	 *
	 * @return the primary key of this view danh sach benh an
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this view danh sach benh an.
	 *
	 * @param primaryKey the primary key of this view danh sach benh an
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this view danh sach benh an.
	 *
	 * @return the ID of this view danh sach benh an
	 */
	public long getId();

	/**
	 * Sets the ID of this view danh sach benh an.
	 *
	 * @param id the ID of this view danh sach benh an
	 */
	public void setId(long id);

	/**
	 * Returns the org ID of this view danh sach benh an.
	 *
	 * @return the org ID of this view danh sach benh an
	 */
	public long getOrgId();

	/**
	 * Sets the org ID of this view danh sach benh an.
	 *
	 * @param orgId the org ID of this view danh sach benh an
	 */
	public void setOrgId(long orgId);

	/**
	 * Returns the ma co so of this view danh sach benh an.
	 *
	 * @return the ma co so of this view danh sach benh an
	 */
	@AutoEscape
	public String getMaCoSo();

	/**
	 * Sets the ma co so of this view danh sach benh an.
	 *
	 * @param maCoSo the ma co so of this view danh sach benh an
	 */
	public void setMaCoSo(String maCoSo);

	/**
	 * Returns the ten co so of this view danh sach benh an.
	 *
	 * @return the ten co so of this view danh sach benh an
	 */
	@AutoEscape
	public String getTenCoSo();

	/**
	 * Sets the ten co so of this view danh sach benh an.
	 *
	 * @param tenCoSo the ten co so of this view danh sach benh an
	 */
	public void setTenCoSo(String tenCoSo);

	/**
	 * Returns the ma ho so of this view danh sach benh an.
	 *
	 * @return the ma ho so of this view danh sach benh an
	 */
	@AutoEscape
	public String getMaHoSo();

	/**
	 * Sets the ma ho so of this view danh sach benh an.
	 *
	 * @param maHoSo the ma ho so of this view danh sach benh an
	 */
	public void setMaHoSo(String maHoSo);

	/**
	 * Returns the ma benh nhan of this view danh sach benh an.
	 *
	 * @return the ma benh nhan of this view danh sach benh an
	 */
	@AutoEscape
	public String getMaBenhNhan();

	/**
	 * Sets the ma benh nhan of this view danh sach benh an.
	 *
	 * @param maBenhNhan the ma benh nhan of this view danh sach benh an
	 */
	public void setMaBenhNhan(String maBenhNhan);

	/**
	 * Returns the ho ten of this view danh sach benh an.
	 *
	 * @return the ho ten of this view danh sach benh an
	 */
	@AutoEscape
	public String getHoTen();

	/**
	 * Sets the ho ten of this view danh sach benh an.
	 *
	 * @param hoTen the ho ten of this view danh sach benh an
	 */
	public void setHoTen(String hoTen);

	/**
	 * Returns the ma the of this view danh sach benh an.
	 *
	 * @return the ma the of this view danh sach benh an
	 */
	@AutoEscape
	public String getMaThe();

	/**
	 * Sets the ma the of this view danh sach benh an.
	 *
	 * @param maThe the ma the of this view danh sach benh an
	 */
	public void setMaThe(String maThe);

	/**
	 * Returns the nam of this view danh sach benh an.
	 *
	 * @return the nam of this view danh sach benh an
	 */
	public int getNam();

	/**
	 * Sets the nam of this view danh sach benh an.
	 *
	 * @param nam the nam of this view danh sach benh an
	 */
	public void setNam(int nam);

	/**
	 * Returns the chi phi of this view danh sach benh an.
	 *
	 * @return the chi phi of this view danh sach benh an
	 */
	public double getChiPhi();

	/**
	 * Sets the chi phi of this view danh sach benh an.
	 *
	 * @param chiPhi the chi phi of this view danh sach benh an
	 */
	public void setChiPhi(double chiPhi);

	/**
	 * Returns the dinh suat of this view danh sach benh an.
	 *
	 * @return the dinh suat of this view danh sach benh an
	 */
	public double getDinhSuat();

	/**
	 * Sets the dinh suat of this view danh sach benh an.
	 *
	 * @param dinhSuat the dinh suat of this view danh sach benh an
	 */
	public void setDinhSuat(double dinhSuat);

	/**
	 * Returns the gia tri of this view danh sach benh an.
	 *
	 * @return the gia tri of this view danh sach benh an
	 */
	public double getGiaTri();

	/**
	 * Sets the gia tri of this view danh sach benh an.
	 *
	 * @param giaTri the gia tri of this view danh sach benh an
	 */
	public void setGiaTri(double giaTri);

}