//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.10.30 at 10:21:49 AM ICT 
//


package com.dtt.lgsp.entities;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="THONGTINDONVI">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="MACSKCB" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="THONGTINHOSO">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="NGAYLAP" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/>
 *                   &lt;element name="SOLUONGHOSO" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
 *                   &lt;element name="DANHSACHHOSO">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="HOSO" maxOccurs="unbounded">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="FILEHOSO" maxOccurs="unbounded">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="LOAIHOSO" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="NOIDUNGFILE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="CHUKYDONVI" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "thongtindonvi",
    "thongtinhoso",
    "chukydonvi"
})
@XmlRootElement(name = "GIAMDINHHS")
public class GIAMDINHHS {

    @XmlElement(name = "THONGTINDONVI", required = true)
    protected GIAMDINHHS.THONGTINDONVI thongtindonvi;
    @XmlElement(name = "THONGTINHOSO", required = true)
    protected GIAMDINHHS.THONGTINHOSO thongtinhoso;
    @XmlElement(name = "CHUKYDONVI", required = true)
    protected Object chukydonvi;

    /**
     * Gets the value of the thongtindonvi property.
     * 
     * @return
     *     possible object is
     *     {@link GIAMDINHHS.THONGTINDONVI }
     *     
     */
    public GIAMDINHHS.THONGTINDONVI getTHONGTINDONVI() {
        return thongtindonvi;
    }

    /**
     * Sets the value of the thongtindonvi property.
     * 
     * @param value
     *     allowed object is
     *     {@link GIAMDINHHS.THONGTINDONVI }
     *     
     */
    public void setTHONGTINDONVI(GIAMDINHHS.THONGTINDONVI value) {
        this.thongtindonvi = value;
    }

    /**
     * Gets the value of the thongtinhoso property.
     * 
     * @return
     *     possible object is
     *     {@link GIAMDINHHS.THONGTINHOSO }
     *     
     */
    public GIAMDINHHS.THONGTINHOSO getTHONGTINHOSO() {
        return thongtinhoso;
    }

    /**
     * Sets the value of the thongtinhoso property.
     * 
     * @param value
     *     allowed object is
     *     {@link GIAMDINHHS.THONGTINHOSO }
     *     
     */
    public void setTHONGTINHOSO(GIAMDINHHS.THONGTINHOSO value) {
        this.thongtinhoso = value;
    }

    /**
     * Gets the value of the chukydonvi property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getCHUKYDONVI() {
        return chukydonvi;
    }

    /**
     * Sets the value of the chukydonvi property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setCHUKYDONVI(Object value) {
        this.chukydonvi = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="MACSKCB" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "macskcb"
    })
    public static class THONGTINDONVI {

        @XmlElement(name = "MACSKCB")
        @XmlSchemaType(name = "unsignedInt")
        protected long macskcb;

        /**
         * Gets the value of the macskcb property.
         * 
         */
        public long getMACSKCB() {
            return macskcb;
        }

        /**
         * Sets the value of the macskcb property.
         * 
         */
        public void setMACSKCB(long value) {
            this.macskcb = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="NGAYLAP" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/>
     *         &lt;element name="SOLUONGHOSO" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
     *         &lt;element name="DANHSACHHOSO">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="HOSO" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="FILEHOSO" maxOccurs="unbounded">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="LOAIHOSO" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="NOIDUNGFILE" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "ngaylap",
        "soluonghoso",
        "danhsachhoso"
    })
    public static class THONGTINHOSO {

        @XmlElement(name = "NGAYLAP")
        @XmlSchemaType(name = "unsignedInt")
        protected long ngaylap;
        @XmlElement(name = "SOLUONGHOSO")
        @XmlSchemaType(name = "unsignedByte")
        protected short soluonghoso;
        @XmlElement(name = "DANHSACHHOSO", required = true)
        protected GIAMDINHHS.THONGTINHOSO.DANHSACHHOSO danhsachhoso;

        /**
         * Gets the value of the ngaylap property.
         * 
         */
        public long getNGAYLAP() {
            return ngaylap;
        }

        /**
         * Sets the value of the ngaylap property.
         * 
         */
        public void setNGAYLAP(long value) {
            this.ngaylap = value;
        }

        /**
         * Gets the value of the soluonghoso property.
         * 
         */
        public short getSOLUONGHOSO() {
            return soluonghoso;
        }

        /**
         * Sets the value of the soluonghoso property.
         * 
         */
        public void setSOLUONGHOSO(short value) {
            this.soluonghoso = value;
        }

        /**
         * Gets the value of the danhsachhoso property.
         * 
         * @return
         *     possible object is
         *     {@link GIAMDINHHS.THONGTINHOSO.DANHSACHHOSO }
         *     
         */
        public GIAMDINHHS.THONGTINHOSO.DANHSACHHOSO getDANHSACHHOSO() {
            return danhsachhoso;
        }

        /**
         * Sets the value of the danhsachhoso property.
         * 
         * @param value
         *     allowed object is
         *     {@link GIAMDINHHS.THONGTINHOSO.DANHSACHHOSO }
         *     
         */
        public void setDANHSACHHOSO(GIAMDINHHS.THONGTINHOSO.DANHSACHHOSO value) {
            this.danhsachhoso = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="HOSO" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="FILEHOSO" maxOccurs="unbounded">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="LOAIHOSO" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="NOIDUNGFILE" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "hoso"
        })
        public static class DANHSACHHOSO {

            @XmlElement(name = "HOSO", required = true)
            public List<GIAMDINHHS.THONGTINHOSO.DANHSACHHOSO.HOSO> hoso;

            /**
             * Gets the value of the hoso property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the hoso property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getHOSO().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link GIAMDINHHS.THONGTINHOSO.DANHSACHHOSO.HOSO }
             * 
             * 
             */
            public List<GIAMDINHHS.THONGTINHOSO.DANHSACHHOSO.HOSO> getHOSO() {
                if (hoso == null) {
                    hoso = new ArrayList<GIAMDINHHS.THONGTINHOSO.DANHSACHHOSO.HOSO>();
                }
                return this.hoso;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="FILEHOSO" maxOccurs="unbounded">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="LOAIHOSO" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="NOIDUNGFILE" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "filehoso"
            })
            public static class HOSO {

                @XmlElement(name = "FILEHOSO", required = true)
                public List<GIAMDINHHS.THONGTINHOSO.DANHSACHHOSO.HOSO.FILEHOSO> filehoso;

                /**
                 * Gets the value of the filehoso property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the filehoso property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getFILEHOSO().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link GIAMDINHHS.THONGTINHOSO.DANHSACHHOSO.HOSO.FILEHOSO }
                 * 
                 * 
                 */
                public List<GIAMDINHHS.THONGTINHOSO.DANHSACHHOSO.HOSO.FILEHOSO> getFILEHOSO() {
                    if (filehoso == null) {
                        filehoso = new ArrayList<GIAMDINHHS.THONGTINHOSO.DANHSACHHOSO.HOSO.FILEHOSO>();
                    }
                    return this.filehoso;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="LOAIHOSO" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="NOIDUNGFILE" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "loaihoso",
                    "noidungfile"
                })
                public static class FILEHOSO {

                    @XmlElement(name = "LOAIHOSO", required = true)
                    protected String loaihoso;
                    @XmlElement(name = "NOIDUNGFILE", required = true)
                    protected String noidungfile;

                    /**
                     * Gets the value of the loaihoso property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getLOAIHOSO() {
                        return loaihoso;
                    }

                    /**
                     * Sets the value of the loaihoso property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setLOAIHOSO(String value) {
                        this.loaihoso = value;
                    }

                    /**
                     * Gets the value of the noidungfile property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getNOIDUNGFILE() {
                        return noidungfile;
                    }

                    /**
                     * Sets the value of the noidungfile property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setNOIDUNGFILE(String value) {
                        this.noidungfile = value;
                    }

                }

            }

        }

    }

}
