//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.10.30 at 10:21:49 AM ICT 
//


package com.dtt.lgsp.entities;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GIAMDINHHS }
     * 
     */
    public GIAMDINHHS createGIAMDINHHS() {
        return new GIAMDINHHS();
    }

    /**
     * Create an instance of {@link GIAMDINHHS.THONGTINHOSO }
     * 
     */
    public GIAMDINHHS.THONGTINHOSO createGIAMDINHHSTHONGTINHOSO() {
        return new GIAMDINHHS.THONGTINHOSO();
    }

    /**
     * Create an instance of {@link GIAMDINHHS.THONGTINHOSO.DANHSACHHOSO }
     * 
     */
    public GIAMDINHHS.THONGTINHOSO.DANHSACHHOSO createGIAMDINHHSTHONGTINHOSODANHSACHHOSO() {
        return new GIAMDINHHS.THONGTINHOSO.DANHSACHHOSO();
    }

    /**
     * Create an instance of {@link GIAMDINHHS.THONGTINHOSO.DANHSACHHOSO.HOSO }
     * 
     */
    public GIAMDINHHS.THONGTINHOSO.DANHSACHHOSO.HOSO createGIAMDINHHSTHONGTINHOSODANHSACHHOSOHOSO() {
        return new GIAMDINHHS.THONGTINHOSO.DANHSACHHOSO.HOSO();
    }

    /**
     * Create an instance of {@link GIAMDINHHS.THONGTINDONVI }
     * 
     */
    public GIAMDINHHS.THONGTINDONVI createGIAMDINHHSTHONGTINDONVI() {
        return new GIAMDINHHS.THONGTINDONVI();
    }

    /**
     * Create an instance of {@link GIAMDINHHS.THONGTINHOSO.DANHSACHHOSO.HOSO.FILEHOSO }
     * 
     */
    public GIAMDINHHS.THONGTINHOSO.DANHSACHHOSO.HOSO.FILEHOSO createGIAMDINHHSTHONGTINHOSODANHSACHHOSOHOSOFILEHOSO() {
        return new GIAMDINHHS.THONGTINHOSO.DANHSACHHOSO.HOSO.FILEHOSO();
    }

}
