/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package drg.moh.service.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import drg.moh.service.model.RpDashboardDRG;
import drg.moh.service.model.RpDashboardDRGModel;
import drg.moh.service.model.RpDashboardDRGSoap;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the RpDashboardDRG service. Represents a row in the &quot;rp_dashboard_drg&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>RpDashboardDRGModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link RpDashboardDRGImpl}.
 * </p>
 *
 * @author SON
 * @see RpDashboardDRGImpl
 * @generated
 */
@JSON(strict = true)
public class RpDashboardDRGModelImpl
	extends BaseModelImpl<RpDashboardDRG> implements RpDashboardDRGModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a rp dashboard drg model instance should use the <code>RpDashboardDRG</code> interface instead.
	 */
	public static final String TABLE_NAME = "rp_dashboard_drg";

	public static final Object[][] TABLE_COLUMNS = {
		{"_id", Types.BIGINT}, {"_drg", Types.VARCHAR},
		{"_thang", Types.VARCHAR}, {"_value", Types.DOUBLE}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("_drg", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("_thang", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("_value", Types.DOUBLE);
	}

	public static final String TABLE_SQL_CREATE =
		"create table rp_dashboard_drg (_id LONG not null primary key,_drg VARCHAR(75) null,_thang VARCHAR(75) null,_value DOUBLE)";

	public static final String TABLE_SQL_DROP = "drop table rp_dashboard_drg";

	public static final String ORDER_BY_JPQL =
		" ORDER BY rpDashboardDRG.id ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY rp_dashboard_drg._id ASC";

	public static final String DATA_SOURCE = "drgDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean ENTITY_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean FINDER_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean COLUMN_BITMASK_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ID_COLUMN_BITMASK = 1L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static RpDashboardDRG toModel(RpDashboardDRGSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		RpDashboardDRG model = new RpDashboardDRGImpl();

		model.setId(soapModel.getId());
		model.setDrg(soapModel.getDrg());
		model.setThang(soapModel.getThang());
		model.setValue(soapModel.getValue());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<RpDashboardDRG> toModels(
		RpDashboardDRGSoap[] soapModels) {

		if (soapModels == null) {
			return null;
		}

		List<RpDashboardDRG> models = new ArrayList<RpDashboardDRG>(
			soapModels.length);

		for (RpDashboardDRGSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		drg.moh.service.service.util.ServiceProps.get(
			"lock.expiration.time.drg.moh.service.model.RpDashboardDRG"));

	public RpDashboardDRGModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return RpDashboardDRG.class;
	}

	@Override
	public String getModelClassName() {
		return RpDashboardDRG.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<RpDashboardDRG, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<RpDashboardDRG, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<RpDashboardDRG, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((RpDashboardDRG)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<RpDashboardDRG, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<RpDashboardDRG, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(RpDashboardDRG)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<RpDashboardDRG, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<RpDashboardDRG, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, RpDashboardDRG>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			RpDashboardDRG.class.getClassLoader(), RpDashboardDRG.class,
			ModelWrapper.class);

		try {
			Constructor<RpDashboardDRG> constructor =
				(Constructor<RpDashboardDRG>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<RpDashboardDRG, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<RpDashboardDRG, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<RpDashboardDRG, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<RpDashboardDRG, Object>>();
		Map<String, BiConsumer<RpDashboardDRG, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<RpDashboardDRG, ?>>();

		attributeGetterFunctions.put("id", RpDashboardDRG::getId);
		attributeSetterBiConsumers.put(
			"id", (BiConsumer<RpDashboardDRG, Long>)RpDashboardDRG::setId);
		attributeGetterFunctions.put("drg", RpDashboardDRG::getDrg);
		attributeSetterBiConsumers.put(
			"drg", (BiConsumer<RpDashboardDRG, String>)RpDashboardDRG::setDrg);
		attributeGetterFunctions.put("thang", RpDashboardDRG::getThang);
		attributeSetterBiConsumers.put(
			"thang",
			(BiConsumer<RpDashboardDRG, String>)RpDashboardDRG::setThang);
		attributeGetterFunctions.put("value", RpDashboardDRG::getValue);
		attributeSetterBiConsumers.put(
			"value",
			(BiConsumer<RpDashboardDRG, Double>)RpDashboardDRG::setValue);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_id = id;
	}

	@JSON
	@Override
	public String getDrg() {
		if (_drg == null) {
			return "";
		}
		else {
			return _drg;
		}
	}

	@Override
	public void setDrg(String drg) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_drg = drg;
	}

	@JSON
	@Override
	public String getThang() {
		if (_thang == null) {
			return "";
		}
		else {
			return _thang;
		}
	}

	@Override
	public void setThang(String thang) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_thang = thang;
	}

	@JSON
	@Override
	public double getValue() {
		return _value;
	}

	@Override
	public void setValue(double value) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_value = value;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (entry.getValue() != getColumnValue(entry.getKey())) {
				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, RpDashboardDRG.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public RpDashboardDRG toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, RpDashboardDRG>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		RpDashboardDRGImpl rpDashboardDRGImpl = new RpDashboardDRGImpl();

		rpDashboardDRGImpl.setId(getId());
		rpDashboardDRGImpl.setDrg(getDrg());
		rpDashboardDRGImpl.setThang(getThang());
		rpDashboardDRGImpl.setValue(getValue());

		rpDashboardDRGImpl.resetOriginalValues();

		return rpDashboardDRGImpl;
	}

	@Override
	public int compareTo(RpDashboardDRG rpDashboardDRG) {
		long primaryKey = rpDashboardDRG.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof RpDashboardDRG)) {
			return false;
		}

		RpDashboardDRG rpDashboardDRG = (RpDashboardDRG)object;

		long primaryKey = rpDashboardDRG.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<RpDashboardDRG> toCacheModel() {
		RpDashboardDRGCacheModel rpDashboardDRGCacheModel =
			new RpDashboardDRGCacheModel();

		rpDashboardDRGCacheModel.id = getId();

		rpDashboardDRGCacheModel.drg = getDrg();

		String drg = rpDashboardDRGCacheModel.drg;

		if ((drg != null) && (drg.length() == 0)) {
			rpDashboardDRGCacheModel.drg = null;
		}

		rpDashboardDRGCacheModel.thang = getThang();

		String thang = rpDashboardDRGCacheModel.thang;

		if ((thang != null) && (thang.length() == 0)) {
			rpDashboardDRGCacheModel.thang = null;
		}

		rpDashboardDRGCacheModel.value = getValue();

		return rpDashboardDRGCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<RpDashboardDRG, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(4 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<RpDashboardDRG, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<RpDashboardDRG, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((RpDashboardDRG)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<RpDashboardDRG, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<RpDashboardDRG, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<RpDashboardDRG, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((RpDashboardDRG)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, RpDashboardDRG>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private long _id;
	private String _drg;
	private String _thang;
	private double _value;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<RpDashboardDRG, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((RpDashboardDRG)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("_id", _id);
		_columnOriginalValues.put("_drg", _drg);
		_columnOriginalValues.put("_thang", _thang);
		_columnOriginalValues.put("_value", _value);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("_id", "id");
		attributeNames.put("_drg", "drg");
		attributeNames.put("_thang", "thang");
		attributeNames.put("_value", "value");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("_id", 1L);

		columnBitmasks.put("_drg", 2L);

		columnBitmasks.put("_thang", 4L);

		columnBitmasks.put("_value", 8L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private RpDashboardDRG _escapedModel;

}