/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package drg.moh.service.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import drg.moh.service.model.RpDashboardCmi3;
import drg.moh.service.model.RpDashboardCmi3Model;
import drg.moh.service.model.RpDashboardCmi3Soap;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the RpDashboardCmi3 service. Represents a row in the &quot;func_dashboard_cmi_3&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>RpDashboardCmi3Model</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link RpDashboardCmi3Impl}.
 * </p>
 *
 * @author SON
 * @see RpDashboardCmi3Impl
 * @generated
 */
@JSON(strict = true)
public class RpDashboardCmi3ModelImpl
	extends BaseModelImpl<RpDashboardCmi3> implements RpDashboardCmi3Model {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a rp dashboard cmi3 model instance should use the <code>RpDashboardCmi3</code> interface instead.
	 */
	public static final String TABLE_NAME = "func_dashboard_cmi_3";

	public static final Object[][] TABLE_COLUMNS = {
		{"_id", Types.BIGINT}, {"_cmi_tinh", Types.DOUBLE},
		{"_cmi_tuyen", Types.DOUBLE}, {"_cmi_coso", Types.DOUBLE}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("_cmi_tinh", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("_cmi_tuyen", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("_cmi_coso", Types.DOUBLE);
	}

	public static final String TABLE_SQL_CREATE =
		"create table func_dashboard_cmi_3 (_id LONG not null primary key,_cmi_tinh DOUBLE,_cmi_tuyen DOUBLE,_cmi_coso DOUBLE)";

	public static final String TABLE_SQL_DROP =
		"drop table func_dashboard_cmi_3";

	public static final String ORDER_BY_JPQL =
		" ORDER BY rpDashboardCmi3.id ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY func_dashboard_cmi_3._id ASC";

	public static final String DATA_SOURCE = "drgDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean ENTITY_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean FINDER_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean COLUMN_BITMASK_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ID_COLUMN_BITMASK = 1L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static RpDashboardCmi3 toModel(RpDashboardCmi3Soap soapModel) {
		if (soapModel == null) {
			return null;
		}

		RpDashboardCmi3 model = new RpDashboardCmi3Impl();

		model.setId(soapModel.getId());
		model.setCmiTinh(soapModel.getCmiTinh());
		model.setCmiTuyen(soapModel.getCmiTuyen());
		model.setCmiCoSo(soapModel.getCmiCoSo());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<RpDashboardCmi3> toModels(
		RpDashboardCmi3Soap[] soapModels) {

		if (soapModels == null) {
			return null;
		}

		List<RpDashboardCmi3> models = new ArrayList<RpDashboardCmi3>(
			soapModels.length);

		for (RpDashboardCmi3Soap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		drg.moh.service.service.util.ServiceProps.get(
			"lock.expiration.time.drg.moh.service.model.RpDashboardCmi3"));

	public RpDashboardCmi3ModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return RpDashboardCmi3.class;
	}

	@Override
	public String getModelClassName() {
		return RpDashboardCmi3.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<RpDashboardCmi3, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<RpDashboardCmi3, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<RpDashboardCmi3, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((RpDashboardCmi3)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<RpDashboardCmi3, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<RpDashboardCmi3, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(RpDashboardCmi3)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<RpDashboardCmi3, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<RpDashboardCmi3, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, RpDashboardCmi3>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			RpDashboardCmi3.class.getClassLoader(), RpDashboardCmi3.class,
			ModelWrapper.class);

		try {
			Constructor<RpDashboardCmi3> constructor =
				(Constructor<RpDashboardCmi3>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<RpDashboardCmi3, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<RpDashboardCmi3, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<RpDashboardCmi3, Object>>
			attributeGetterFunctions =
				new LinkedHashMap<String, Function<RpDashboardCmi3, Object>>();
		Map<String, BiConsumer<RpDashboardCmi3, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<RpDashboardCmi3, ?>>();

		attributeGetterFunctions.put("id", RpDashboardCmi3::getId);
		attributeSetterBiConsumers.put(
			"id", (BiConsumer<RpDashboardCmi3, Long>)RpDashboardCmi3::setId);
		attributeGetterFunctions.put("cmiTinh", RpDashboardCmi3::getCmiTinh);
		attributeSetterBiConsumers.put(
			"cmiTinh",
			(BiConsumer<RpDashboardCmi3, Double>)RpDashboardCmi3::setCmiTinh);
		attributeGetterFunctions.put("cmiTuyen", RpDashboardCmi3::getCmiTuyen);
		attributeSetterBiConsumers.put(
			"cmiTuyen",
			(BiConsumer<RpDashboardCmi3, Double>)RpDashboardCmi3::setCmiTuyen);
		attributeGetterFunctions.put("cmiCoSo", RpDashboardCmi3::getCmiCoSo);
		attributeSetterBiConsumers.put(
			"cmiCoSo",
			(BiConsumer<RpDashboardCmi3, Double>)RpDashboardCmi3::setCmiCoSo);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_id = id;
	}

	@JSON
	@Override
	public double getCmiTinh() {
		return _cmiTinh;
	}

	@Override
	public void setCmiTinh(double cmiTinh) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_cmiTinh = cmiTinh;
	}

	@JSON
	@Override
	public double getCmiTuyen() {
		return _cmiTuyen;
	}

	@Override
	public void setCmiTuyen(double cmiTuyen) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_cmiTuyen = cmiTuyen;
	}

	@JSON
	@Override
	public double getCmiCoSo() {
		return _cmiCoSo;
	}

	@Override
	public void setCmiCoSo(double cmiCoSo) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_cmiCoSo = cmiCoSo;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (entry.getValue() != getColumnValue(entry.getKey())) {
				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, RpDashboardCmi3.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public RpDashboardCmi3 toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, RpDashboardCmi3>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		RpDashboardCmi3Impl rpDashboardCmi3Impl = new RpDashboardCmi3Impl();

		rpDashboardCmi3Impl.setId(getId());
		rpDashboardCmi3Impl.setCmiTinh(getCmiTinh());
		rpDashboardCmi3Impl.setCmiTuyen(getCmiTuyen());
		rpDashboardCmi3Impl.setCmiCoSo(getCmiCoSo());

		rpDashboardCmi3Impl.resetOriginalValues();

		return rpDashboardCmi3Impl;
	}

	@Override
	public int compareTo(RpDashboardCmi3 rpDashboardCmi3) {
		long primaryKey = rpDashboardCmi3.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof RpDashboardCmi3)) {
			return false;
		}

		RpDashboardCmi3 rpDashboardCmi3 = (RpDashboardCmi3)object;

		long primaryKey = rpDashboardCmi3.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<RpDashboardCmi3> toCacheModel() {
		RpDashboardCmi3CacheModel rpDashboardCmi3CacheModel =
			new RpDashboardCmi3CacheModel();

		rpDashboardCmi3CacheModel.id = getId();

		rpDashboardCmi3CacheModel.cmiTinh = getCmiTinh();

		rpDashboardCmi3CacheModel.cmiTuyen = getCmiTuyen();

		rpDashboardCmi3CacheModel.cmiCoSo = getCmiCoSo();

		return rpDashboardCmi3CacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<RpDashboardCmi3, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(4 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<RpDashboardCmi3, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<RpDashboardCmi3, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((RpDashboardCmi3)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<RpDashboardCmi3, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<RpDashboardCmi3, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<RpDashboardCmi3, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((RpDashboardCmi3)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, RpDashboardCmi3>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private long _id;
	private double _cmiTinh;
	private double _cmiTuyen;
	private double _cmiCoSo;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<RpDashboardCmi3, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((RpDashboardCmi3)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("_id", _id);
		_columnOriginalValues.put("_cmi_tinh", _cmiTinh);
		_columnOriginalValues.put("_cmi_tuyen", _cmiTuyen);
		_columnOriginalValues.put("_cmi_coso", _cmiCoSo);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("_id", "id");
		attributeNames.put("_cmi_tinh", "cmiTinh");
		attributeNames.put("_cmi_tuyen", "cmiTuyen");
		attributeNames.put("_cmi_coso", "cmiCoSo");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("_id", 1L);

		columnBitmasks.put("_cmi_tinh", 2L);

		columnBitmasks.put("_cmi_tuyen", 4L);

		columnBitmasks.put("_cmi_coso", 8L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private RpDashboardCmi3 _escapedModel;

}