/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package drg.moh.service.model.impl;

import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import drg.moh.service.model.RpDashboardDstcChiTiet;
import drg.moh.service.model.RpDashboardDstcChiTietModel;
import drg.moh.service.model.RpDashboardDstcChiTietSoap;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the RpDashboardDstcChiTiet service. Represents a row in the &quot;rp_dashboard_dstc_chitiet&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>RpDashboardDstcChiTietModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link RpDashboardDstcChiTietImpl}.
 * </p>
 *
 * @author SON
 * @see RpDashboardDstcChiTietImpl
 * @generated
 */
@JSON(strict = true)
public class RpDashboardDstcChiTietModelImpl
	extends BaseModelImpl<RpDashboardDstcChiTiet>
	implements RpDashboardDstcChiTietModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a rp dashboard dstc chi tiet model instance should use the <code>RpDashboardDstcChiTiet</code> interface instead.
	 */
	public static final String TABLE_NAME = "rp_dashboard_dstc_chitiet";

	public static final Object[][] TABLE_COLUMNS = {
		{"_id", Types.VARCHAR}, {"_ten_tinh", Types.VARCHAR},
		{"_dinhsuat", Types.INTEGER}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("_id", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("_ten_tinh", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("_dinhsuat", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE =
		"create table rp_dashboard_dstc_chitiet (_id VARCHAR(75) not null primary key,_ten_tinh VARCHAR(75) null,_dinhsuat INTEGER)";

	public static final String TABLE_SQL_DROP =
		"drop table rp_dashboard_dstc_chitiet";

	public static final String ORDER_BY_JPQL =
		" ORDER BY rpDashboardDstcChiTiet.id ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY rp_dashboard_dstc_chitiet._id ASC";

	public static final String DATA_SOURCE = "drgDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean ENTITY_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean FINDER_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean COLUMN_BITMASK_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ID_COLUMN_BITMASK = 1L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static RpDashboardDstcChiTiet toModel(
		RpDashboardDstcChiTietSoap soapModel) {

		if (soapModel == null) {
			return null;
		}

		RpDashboardDstcChiTiet model = new RpDashboardDstcChiTietImpl();

		model.setId(soapModel.getId());
		model.setTenTinh(soapModel.getTenTinh());
		model.setDinhSuat(soapModel.getDinhSuat());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<RpDashboardDstcChiTiet> toModels(
		RpDashboardDstcChiTietSoap[] soapModels) {

		if (soapModels == null) {
			return null;
		}

		List<RpDashboardDstcChiTiet> models =
			new ArrayList<RpDashboardDstcChiTiet>(soapModels.length);

		for (RpDashboardDstcChiTietSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		drg.moh.service.service.util.ServiceProps.get(
			"lock.expiration.time.drg.moh.service.model.RpDashboardDstcChiTiet"));

	public RpDashboardDstcChiTietModelImpl() {
	}

	@Override
	public String getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(String primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((String)primaryKeyObj);
	}

	@Override
	public Class<?> getModelClass() {
		return RpDashboardDstcChiTiet.class;
	}

	@Override
	public String getModelClassName() {
		return RpDashboardDstcChiTiet.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<RpDashboardDstcChiTiet, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<RpDashboardDstcChiTiet, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<RpDashboardDstcChiTiet, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((RpDashboardDstcChiTiet)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<RpDashboardDstcChiTiet, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<RpDashboardDstcChiTiet, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(RpDashboardDstcChiTiet)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<RpDashboardDstcChiTiet, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<RpDashboardDstcChiTiet, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, RpDashboardDstcChiTiet>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			RpDashboardDstcChiTiet.class.getClassLoader(),
			RpDashboardDstcChiTiet.class, ModelWrapper.class);

		try {
			Constructor<RpDashboardDstcChiTiet> constructor =
				(Constructor<RpDashboardDstcChiTiet>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<RpDashboardDstcChiTiet, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<RpDashboardDstcChiTiet, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<RpDashboardDstcChiTiet, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<RpDashboardDstcChiTiet, Object>>();
		Map<String, BiConsumer<RpDashboardDstcChiTiet, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap
					<String, BiConsumer<RpDashboardDstcChiTiet, ?>>();

		attributeGetterFunctions.put("id", RpDashboardDstcChiTiet::getId);
		attributeSetterBiConsumers.put(
			"id",
			(BiConsumer<RpDashboardDstcChiTiet, String>)
				RpDashboardDstcChiTiet::setId);
		attributeGetterFunctions.put(
			"tenTinh", RpDashboardDstcChiTiet::getTenTinh);
		attributeSetterBiConsumers.put(
			"tenTinh",
			(BiConsumer<RpDashboardDstcChiTiet, String>)
				RpDashboardDstcChiTiet::setTenTinh);
		attributeGetterFunctions.put(
			"dinhSuat", RpDashboardDstcChiTiet::getDinhSuat);
		attributeSetterBiConsumers.put(
			"dinhSuat",
			(BiConsumer<RpDashboardDstcChiTiet, Integer>)
				RpDashboardDstcChiTiet::setDinhSuat);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getId() {
		if (_id == null) {
			return "";
		}
		else {
			return _id;
		}
	}

	@Override
	public void setId(String id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_id = id;
	}

	@JSON
	@Override
	public String getTenTinh() {
		if (_tenTinh == null) {
			return "";
		}
		else {
			return _tenTinh;
		}
	}

	@Override
	public void setTenTinh(String tenTinh) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_tenTinh = tenTinh;
	}

	@JSON
	@Override
	public int getDinhSuat() {
		return _dinhSuat;
	}

	@Override
	public void setDinhSuat(int dinhSuat) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_dinhSuat = dinhSuat;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (entry.getValue() != getColumnValue(entry.getKey())) {
				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public RpDashboardDstcChiTiet toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, RpDashboardDstcChiTiet>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		RpDashboardDstcChiTietImpl rpDashboardDstcChiTietImpl =
			new RpDashboardDstcChiTietImpl();

		rpDashboardDstcChiTietImpl.setId(getId());
		rpDashboardDstcChiTietImpl.setTenTinh(getTenTinh());
		rpDashboardDstcChiTietImpl.setDinhSuat(getDinhSuat());

		rpDashboardDstcChiTietImpl.resetOriginalValues();

		return rpDashboardDstcChiTietImpl;
	}

	@Override
	public int compareTo(RpDashboardDstcChiTiet rpDashboardDstcChiTiet) {
		String primaryKey = rpDashboardDstcChiTiet.getPrimaryKey();

		return getPrimaryKey().compareTo(primaryKey);
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof RpDashboardDstcChiTiet)) {
			return false;
		}

		RpDashboardDstcChiTiet rpDashboardDstcChiTiet =
			(RpDashboardDstcChiTiet)object;

		String primaryKey = rpDashboardDstcChiTiet.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<RpDashboardDstcChiTiet> toCacheModel() {
		RpDashboardDstcChiTietCacheModel rpDashboardDstcChiTietCacheModel =
			new RpDashboardDstcChiTietCacheModel();

		rpDashboardDstcChiTietCacheModel.id = getId();

		String id = rpDashboardDstcChiTietCacheModel.id;

		if ((id != null) && (id.length() == 0)) {
			rpDashboardDstcChiTietCacheModel.id = null;
		}

		rpDashboardDstcChiTietCacheModel.tenTinh = getTenTinh();

		String tenTinh = rpDashboardDstcChiTietCacheModel.tenTinh;

		if ((tenTinh != null) && (tenTinh.length() == 0)) {
			rpDashboardDstcChiTietCacheModel.tenTinh = null;
		}

		rpDashboardDstcChiTietCacheModel.dinhSuat = getDinhSuat();

		return rpDashboardDstcChiTietCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<RpDashboardDstcChiTiet, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(4 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<RpDashboardDstcChiTiet, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<RpDashboardDstcChiTiet, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(
				attributeGetterFunction.apply((RpDashboardDstcChiTiet)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<RpDashboardDstcChiTiet, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<RpDashboardDstcChiTiet, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<RpDashboardDstcChiTiet, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(
				attributeGetterFunction.apply((RpDashboardDstcChiTiet)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, RpDashboardDstcChiTiet>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private String _id;
	private String _tenTinh;
	private int _dinhSuat;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<RpDashboardDstcChiTiet, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((RpDashboardDstcChiTiet)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("_id", _id);
		_columnOriginalValues.put("_ten_tinh", _tenTinh);
		_columnOriginalValues.put("_dinhsuat", _dinhSuat);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("_id", "id");
		attributeNames.put("_ten_tinh", "tenTinh");
		attributeNames.put("_dinhsuat", "dinhSuat");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("_id", 1L);

		columnBitmasks.put("_ten_tinh", 2L);

		columnBitmasks.put("_dinhsuat", 4L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private RpDashboardDstcChiTiet _escapedModel;

}