/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package drg.moh.service.model.impl;

import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import drg.moh.service.model.RpDashboardDstc;
import drg.moh.service.model.RpDashboardDstcModel;
import drg.moh.service.model.RpDashboardDstcSoap;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the RpDashboardDstc service. Represents a row in the &quot;rp_dashboard_dstc&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>RpDashboardDstcModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link RpDashboardDstcImpl}.
 * </p>
 *
 * @author SON
 * @see RpDashboardDstcImpl
 * @generated
 */
@JSON(strict = true)
public class RpDashboardDstcModelImpl
	extends BaseModelImpl<RpDashboardDstc> implements RpDashboardDstcModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a rp dashboard dstc model instance should use the <code>RpDashboardDstc</code> interface instead.
	 */
	public static final String TABLE_NAME = "rp_dashboard_dstc";

	public static final Object[][] TABLE_COLUMNS = {
		{"_id", Types.VARCHAR}, {"_ten_tinh", Types.VARCHAR},
		{"_thang", Types.INTEGER}, {"_soluot", Types.INTEGER},
		{"_chiphi", Types.DOUBLE}, {"_quyds", Types.DOUBLE}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("_id", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("_ten_tinh", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("_thang", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("_soluot", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("_chiphi", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("_quyds", Types.DOUBLE);
	}

	public static final String TABLE_SQL_CREATE =
		"create table rp_dashboard_dstc (_id VARCHAR(75) not null primary key,_ten_tinh VARCHAR(75) null,_thang INTEGER,_soluot INTEGER,_chiphi DOUBLE,_quyds DOUBLE)";

	public static final String TABLE_SQL_DROP = "drop table rp_dashboard_dstc";

	public static final String ORDER_BY_JPQL =
		" ORDER BY rpDashboardDstc.id ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY rp_dashboard_dstc._id ASC";

	public static final String DATA_SOURCE = "drgDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean ENTITY_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean FINDER_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean COLUMN_BITMASK_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ID_COLUMN_BITMASK = 1L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static RpDashboardDstc toModel(RpDashboardDstcSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		RpDashboardDstc model = new RpDashboardDstcImpl();

		model.setId(soapModel.getId());
		model.setTenTinh(soapModel.getTenTinh());
		model.setThang(soapModel.getThang());
		model.setSoLuot(soapModel.getSoLuot());
		model.setChiPhi(soapModel.getChiPhi());
		model.setQuyDs(soapModel.getQuyDs());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<RpDashboardDstc> toModels(
		RpDashboardDstcSoap[] soapModels) {

		if (soapModels == null) {
			return null;
		}

		List<RpDashboardDstc> models = new ArrayList<RpDashboardDstc>(
			soapModels.length);

		for (RpDashboardDstcSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		drg.moh.service.service.util.ServiceProps.get(
			"lock.expiration.time.drg.moh.service.model.RpDashboardDstc"));

	public RpDashboardDstcModelImpl() {
	}

	@Override
	public String getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(String primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((String)primaryKeyObj);
	}

	@Override
	public Class<?> getModelClass() {
		return RpDashboardDstc.class;
	}

	@Override
	public String getModelClassName() {
		return RpDashboardDstc.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<RpDashboardDstc, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<RpDashboardDstc, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<RpDashboardDstc, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((RpDashboardDstc)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<RpDashboardDstc, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<RpDashboardDstc, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(RpDashboardDstc)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<RpDashboardDstc, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<RpDashboardDstc, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, RpDashboardDstc>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			RpDashboardDstc.class.getClassLoader(), RpDashboardDstc.class,
			ModelWrapper.class);

		try {
			Constructor<RpDashboardDstc> constructor =
				(Constructor<RpDashboardDstc>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<RpDashboardDstc, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<RpDashboardDstc, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<RpDashboardDstc, Object>>
			attributeGetterFunctions =
				new LinkedHashMap<String, Function<RpDashboardDstc, Object>>();
		Map<String, BiConsumer<RpDashboardDstc, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<RpDashboardDstc, ?>>();

		attributeGetterFunctions.put("id", RpDashboardDstc::getId);
		attributeSetterBiConsumers.put(
			"id", (BiConsumer<RpDashboardDstc, String>)RpDashboardDstc::setId);
		attributeGetterFunctions.put("tenTinh", RpDashboardDstc::getTenTinh);
		attributeSetterBiConsumers.put(
			"tenTinh",
			(BiConsumer<RpDashboardDstc, String>)RpDashboardDstc::setTenTinh);
		attributeGetterFunctions.put("thang", RpDashboardDstc::getThang);
		attributeSetterBiConsumers.put(
			"thang",
			(BiConsumer<RpDashboardDstc, Integer>)RpDashboardDstc::setThang);
		attributeGetterFunctions.put("soLuot", RpDashboardDstc::getSoLuot);
		attributeSetterBiConsumers.put(
			"soLuot",
			(BiConsumer<RpDashboardDstc, Integer>)RpDashboardDstc::setSoLuot);
		attributeGetterFunctions.put("chiPhi", RpDashboardDstc::getChiPhi);
		attributeSetterBiConsumers.put(
			"chiPhi",
			(BiConsumer<RpDashboardDstc, Double>)RpDashboardDstc::setChiPhi);
		attributeGetterFunctions.put("quyDs", RpDashboardDstc::getQuyDs);
		attributeSetterBiConsumers.put(
			"quyDs",
			(BiConsumer<RpDashboardDstc, Double>)RpDashboardDstc::setQuyDs);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getId() {
		if (_id == null) {
			return "";
		}
		else {
			return _id;
		}
	}

	@Override
	public void setId(String id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_id = id;
	}

	@JSON
	@Override
	public String getTenTinh() {
		if (_tenTinh == null) {
			return "";
		}
		else {
			return _tenTinh;
		}
	}

	@Override
	public void setTenTinh(String tenTinh) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_tenTinh = tenTinh;
	}

	@JSON
	@Override
	public int getThang() {
		return _thang;
	}

	@Override
	public void setThang(int thang) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_thang = thang;
	}

	@JSON
	@Override
	public int getSoLuot() {
		return _soLuot;
	}

	@Override
	public void setSoLuot(int soLuot) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_soLuot = soLuot;
	}

	@JSON
	@Override
	public double getChiPhi() {
		return _chiPhi;
	}

	@Override
	public void setChiPhi(double chiPhi) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_chiPhi = chiPhi;
	}

	@JSON
	@Override
	public double getQuyDs() {
		return _quyDs;
	}

	@Override
	public void setQuyDs(double quyDs) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_quyDs = quyDs;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (entry.getValue() != getColumnValue(entry.getKey())) {
				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public RpDashboardDstc toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, RpDashboardDstc>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		RpDashboardDstcImpl rpDashboardDstcImpl = new RpDashboardDstcImpl();

		rpDashboardDstcImpl.setId(getId());
		rpDashboardDstcImpl.setTenTinh(getTenTinh());
		rpDashboardDstcImpl.setThang(getThang());
		rpDashboardDstcImpl.setSoLuot(getSoLuot());
		rpDashboardDstcImpl.setChiPhi(getChiPhi());
		rpDashboardDstcImpl.setQuyDs(getQuyDs());

		rpDashboardDstcImpl.resetOriginalValues();

		return rpDashboardDstcImpl;
	}

	@Override
	public int compareTo(RpDashboardDstc rpDashboardDstc) {
		String primaryKey = rpDashboardDstc.getPrimaryKey();

		return getPrimaryKey().compareTo(primaryKey);
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof RpDashboardDstc)) {
			return false;
		}

		RpDashboardDstc rpDashboardDstc = (RpDashboardDstc)object;

		String primaryKey = rpDashboardDstc.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<RpDashboardDstc> toCacheModel() {
		RpDashboardDstcCacheModel rpDashboardDstcCacheModel =
			new RpDashboardDstcCacheModel();

		rpDashboardDstcCacheModel.id = getId();

		String id = rpDashboardDstcCacheModel.id;

		if ((id != null) && (id.length() == 0)) {
			rpDashboardDstcCacheModel.id = null;
		}

		rpDashboardDstcCacheModel.tenTinh = getTenTinh();

		String tenTinh = rpDashboardDstcCacheModel.tenTinh;

		if ((tenTinh != null) && (tenTinh.length() == 0)) {
			rpDashboardDstcCacheModel.tenTinh = null;
		}

		rpDashboardDstcCacheModel.thang = getThang();

		rpDashboardDstcCacheModel.soLuot = getSoLuot();

		rpDashboardDstcCacheModel.chiPhi = getChiPhi();

		rpDashboardDstcCacheModel.quyDs = getQuyDs();

		return rpDashboardDstcCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<RpDashboardDstc, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(4 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<RpDashboardDstc, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<RpDashboardDstc, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((RpDashboardDstc)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<RpDashboardDstc, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<RpDashboardDstc, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<RpDashboardDstc, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((RpDashboardDstc)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, RpDashboardDstc>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private String _id;
	private String _tenTinh;
	private int _thang;
	private int _soLuot;
	private double _chiPhi;
	private double _quyDs;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<RpDashboardDstc, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((RpDashboardDstc)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("_id", _id);
		_columnOriginalValues.put("_ten_tinh", _tenTinh);
		_columnOriginalValues.put("_thang", _thang);
		_columnOriginalValues.put("_soluot", _soLuot);
		_columnOriginalValues.put("_chiphi", _chiPhi);
		_columnOriginalValues.put("_quyds", _quyDs);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("_id", "id");
		attributeNames.put("_ten_tinh", "tenTinh");
		attributeNames.put("_thang", "thang");
		attributeNames.put("_soluot", "soLuot");
		attributeNames.put("_chiphi", "chiPhi");
		attributeNames.put("_quyds", "quyDs");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("_id", 1L);

		columnBitmasks.put("_ten_tinh", 2L);

		columnBitmasks.put("_thang", 4L);

		columnBitmasks.put("_soluot", 8L);

		columnBitmasks.put("_chiphi", 16L);

		columnBitmasks.put("_quyds", 32L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private RpDashboardDstc _escapedModel;

}