/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package drg.moh.service.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import drg.moh.service.model.RpDashboardDinhSuatChiTiet;
import drg.moh.service.model.RpDashboardDinhSuatChiTietModel;
import drg.moh.service.model.RpDashboardDinhSuatChiTietSoap;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the RpDashboardDinhSuatChiTiet service. Represents a row in the &quot;rp_dashboard_dinhsuat_ct&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>RpDashboardDinhSuatChiTietModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link RpDashboardDinhSuatChiTietImpl}.
 * </p>
 *
 * @author SON
 * @see RpDashboardDinhSuatChiTietImpl
 * @generated
 */
@JSON(strict = true)
public class RpDashboardDinhSuatChiTietModelImpl
	extends BaseModelImpl<RpDashboardDinhSuatChiTiet>
	implements RpDashboardDinhSuatChiTietModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a rp dashboard dinh suat chi tiet model instance should use the <code>RpDashboardDinhSuatChiTiet</code> interface instead.
	 */
	public static final String TABLE_NAME = "rp_dashboard_dinhsuat_ct";

	public static final Object[][] TABLE_COLUMNS = {
		{"_id", Types.BIGINT}, {"_tentinh", Types.VARCHAR},
		{"_dinhsuat", Types.DOUBLE}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("_tentinh", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("_dinhsuat", Types.DOUBLE);
	}

	public static final String TABLE_SQL_CREATE =
		"create table rp_dashboard_dinhsuat_ct (_id LONG not null primary key,_tentinh VARCHAR(75) null,_dinhsuat DOUBLE)";

	public static final String TABLE_SQL_DROP =
		"drop table rp_dashboard_dinhsuat_ct";

	public static final String ORDER_BY_JPQL =
		" ORDER BY rpDashboardDinhSuatChiTiet.id ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY rp_dashboard_dinhsuat_ct._id ASC";

	public static final String DATA_SOURCE = "drgDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean ENTITY_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean FINDER_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean COLUMN_BITMASK_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ID_COLUMN_BITMASK = 1L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static RpDashboardDinhSuatChiTiet toModel(
		RpDashboardDinhSuatChiTietSoap soapModel) {

		if (soapModel == null) {
			return null;
		}

		RpDashboardDinhSuatChiTiet model = new RpDashboardDinhSuatChiTietImpl();

		model.setId(soapModel.getId());
		model.setTenTinh(soapModel.getTenTinh());
		model.setDinhSuat(soapModel.getDinhSuat());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<RpDashboardDinhSuatChiTiet> toModels(
		RpDashboardDinhSuatChiTietSoap[] soapModels) {

		if (soapModels == null) {
			return null;
		}

		List<RpDashboardDinhSuatChiTiet> models =
			new ArrayList<RpDashboardDinhSuatChiTiet>(soapModels.length);

		for (RpDashboardDinhSuatChiTietSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		drg.moh.service.service.util.ServiceProps.get(
			"lock.expiration.time.drg.moh.service.model.RpDashboardDinhSuatChiTiet"));

	public RpDashboardDinhSuatChiTietModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return RpDashboardDinhSuatChiTiet.class;
	}

	@Override
	public String getModelClassName() {
		return RpDashboardDinhSuatChiTiet.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<RpDashboardDinhSuatChiTiet, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<RpDashboardDinhSuatChiTiet, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<RpDashboardDinhSuatChiTiet, Object>
				attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply(
					(RpDashboardDinhSuatChiTiet)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<RpDashboardDinhSuatChiTiet, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<RpDashboardDinhSuatChiTiet, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(RpDashboardDinhSuatChiTiet)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<RpDashboardDinhSuatChiTiet, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<RpDashboardDinhSuatChiTiet, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, RpDashboardDinhSuatChiTiet>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			RpDashboardDinhSuatChiTiet.class.getClassLoader(),
			RpDashboardDinhSuatChiTiet.class, ModelWrapper.class);

		try {
			Constructor<RpDashboardDinhSuatChiTiet> constructor =
				(Constructor<RpDashboardDinhSuatChiTiet>)
					proxyClass.getConstructor(InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map
		<String, Function<RpDashboardDinhSuatChiTiet, Object>>
			_attributeGetterFunctions;
	private static final Map
		<String, BiConsumer<RpDashboardDinhSuatChiTiet, Object>>
			_attributeSetterBiConsumers;

	static {
		Map<String, Function<RpDashboardDinhSuatChiTiet, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<RpDashboardDinhSuatChiTiet, Object>>();
		Map<String, BiConsumer<RpDashboardDinhSuatChiTiet, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap
					<String, BiConsumer<RpDashboardDinhSuatChiTiet, ?>>();

		attributeGetterFunctions.put("id", RpDashboardDinhSuatChiTiet::getId);
		attributeSetterBiConsumers.put(
			"id",
			(BiConsumer<RpDashboardDinhSuatChiTiet, Long>)
				RpDashboardDinhSuatChiTiet::setId);
		attributeGetterFunctions.put(
			"tenTinh", RpDashboardDinhSuatChiTiet::getTenTinh);
		attributeSetterBiConsumers.put(
			"tenTinh",
			(BiConsumer<RpDashboardDinhSuatChiTiet, String>)
				RpDashboardDinhSuatChiTiet::setTenTinh);
		attributeGetterFunctions.put(
			"dinhSuat", RpDashboardDinhSuatChiTiet::getDinhSuat);
		attributeSetterBiConsumers.put(
			"dinhSuat",
			(BiConsumer<RpDashboardDinhSuatChiTiet, Double>)
				RpDashboardDinhSuatChiTiet::setDinhSuat);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_id = id;
	}

	@JSON
	@Override
	public String getTenTinh() {
		if (_tenTinh == null) {
			return "";
		}
		else {
			return _tenTinh;
		}
	}

	@Override
	public void setTenTinh(String tenTinh) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_tenTinh = tenTinh;
	}

	@JSON
	@Override
	public double getDinhSuat() {
		return _dinhSuat;
	}

	@Override
	public void setDinhSuat(double dinhSuat) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_dinhSuat = dinhSuat;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (entry.getValue() != getColumnValue(entry.getKey())) {
				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, RpDashboardDinhSuatChiTiet.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public RpDashboardDinhSuatChiTiet toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, RpDashboardDinhSuatChiTiet>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		RpDashboardDinhSuatChiTietImpl rpDashboardDinhSuatChiTietImpl =
			new RpDashboardDinhSuatChiTietImpl();

		rpDashboardDinhSuatChiTietImpl.setId(getId());
		rpDashboardDinhSuatChiTietImpl.setTenTinh(getTenTinh());
		rpDashboardDinhSuatChiTietImpl.setDinhSuat(getDinhSuat());

		rpDashboardDinhSuatChiTietImpl.resetOriginalValues();

		return rpDashboardDinhSuatChiTietImpl;
	}

	@Override
	public int compareTo(
		RpDashboardDinhSuatChiTiet rpDashboardDinhSuatChiTiet) {

		long primaryKey = rpDashboardDinhSuatChiTiet.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof RpDashboardDinhSuatChiTiet)) {
			return false;
		}

		RpDashboardDinhSuatChiTiet rpDashboardDinhSuatChiTiet =
			(RpDashboardDinhSuatChiTiet)object;

		long primaryKey = rpDashboardDinhSuatChiTiet.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<RpDashboardDinhSuatChiTiet> toCacheModel() {
		RpDashboardDinhSuatChiTietCacheModel
			rpDashboardDinhSuatChiTietCacheModel =
				new RpDashboardDinhSuatChiTietCacheModel();

		rpDashboardDinhSuatChiTietCacheModel.id = getId();

		rpDashboardDinhSuatChiTietCacheModel.tenTinh = getTenTinh();

		String tenTinh = rpDashboardDinhSuatChiTietCacheModel.tenTinh;

		if ((tenTinh != null) && (tenTinh.length() == 0)) {
			rpDashboardDinhSuatChiTietCacheModel.tenTinh = null;
		}

		rpDashboardDinhSuatChiTietCacheModel.dinhSuat = getDinhSuat();

		return rpDashboardDinhSuatChiTietCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<RpDashboardDinhSuatChiTiet, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(4 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<RpDashboardDinhSuatChiTiet, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<RpDashboardDinhSuatChiTiet, Object>
				attributeGetterFunction = entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(
				attributeGetterFunction.apply(
					(RpDashboardDinhSuatChiTiet)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<RpDashboardDinhSuatChiTiet, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<RpDashboardDinhSuatChiTiet, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<RpDashboardDinhSuatChiTiet, Object>
				attributeGetterFunction = entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(
				attributeGetterFunction.apply(
					(RpDashboardDinhSuatChiTiet)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function
			<InvocationHandler, RpDashboardDinhSuatChiTiet>
				_escapedModelProxyProviderFunction =
					_getProxyProviderFunction();

	}

	private long _id;
	private String _tenTinh;
	private double _dinhSuat;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<RpDashboardDinhSuatChiTiet, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((RpDashboardDinhSuatChiTiet)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("_id", _id);
		_columnOriginalValues.put("_tentinh", _tenTinh);
		_columnOriginalValues.put("_dinhsuat", _dinhSuat);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("_id", "id");
		attributeNames.put("_tentinh", "tenTinh");
		attributeNames.put("_dinhsuat", "dinhSuat");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("_id", 1L);

		columnBitmasks.put("_tentinh", 2L);

		columnBitmasks.put("_dinhsuat", 4L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private RpDashboardDinhSuatChiTiet _escapedModel;

}