/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package drg.moh.service.model.impl;

import drg.moh.service.model.RpDashboardCmi3;
import drg.moh.service.service.RpDashboardCmi3LocalServiceUtil;

/**
 * The extended model base implementation for the RpDashboardCmi3 service. Represents a row in the &quot;func_dashboard_cmi_3&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link RpDashboardCmi3Impl}.
 * </p>
 *
 * @author SON
 * @see RpDashboardCmi3Impl
 * @see RpDashboardCmi3
 * @generated
 */
public abstract class RpDashboardCmi3BaseImpl
	extends RpDashboardCmi3ModelImpl implements RpDashboardCmi3 {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a rp dashboard cmi3 model instance should use the <code>RpDashboardCmi3</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			RpDashboardCmi3LocalServiceUtil.addRpDashboardCmi3(this);
		}
		else {
			RpDashboardCmi3LocalServiceUtil.updateRpDashboardCmi3(this);
		}
	}

}