/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package drg.moh.service.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import drg.moh.service.model.RpDashboardCmi2;
import drg.moh.service.model.RpDashboardCmi2Model;
import drg.moh.service.model.RpDashboardCmi2Soap;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the RpDashboardCmi2 service. Represents a row in the &quot;func_dashboard_cmi_2&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>RpDashboardCmi2Model</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link RpDashboardCmi2Impl}.
 * </p>
 *
 * @author SON
 * @see RpDashboardCmi2Impl
 * @generated
 */
@JSON(strict = true)
public class RpDashboardCmi2ModelImpl
	extends BaseModelImpl<RpDashboardCmi2> implements RpDashboardCmi2Model {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a rp dashboard cmi2 model instance should use the <code>RpDashboardCmi2</code> interface instead.
	 */
	public static final String TABLE_NAME = "func_dashboard_cmi_2";

	public static final Object[][] TABLE_COLUMNS = {
		{"_id", Types.BIGINT}, {"_cmi_tentuyen", Types.VARCHAR},
		{"_cmi_trungbinh", Types.DOUBLE}, {"_cmi_max", Types.DOUBLE},
		{"_cmi_min", Types.DOUBLE}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("_cmi_tentuyen", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("_cmi_trungbinh", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("_cmi_max", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("_cmi_min", Types.DOUBLE);
	}

	public static final String TABLE_SQL_CREATE =
		"create table func_dashboard_cmi_2 (_id LONG not null primary key,_cmi_tentuyen VARCHAR(75) null,_cmi_trungbinh DOUBLE,_cmi_max DOUBLE,_cmi_min DOUBLE)";

	public static final String TABLE_SQL_DROP =
		"drop table func_dashboard_cmi_2";

	public static final String ORDER_BY_JPQL =
		" ORDER BY rpDashboardCmi2.id ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY func_dashboard_cmi_2._id ASC";

	public static final String DATA_SOURCE = "drgDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean ENTITY_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean FINDER_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean COLUMN_BITMASK_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ID_COLUMN_BITMASK = 1L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static RpDashboardCmi2 toModel(RpDashboardCmi2Soap soapModel) {
		if (soapModel == null) {
			return null;
		}

		RpDashboardCmi2 model = new RpDashboardCmi2Impl();

		model.setId(soapModel.getId());
		model.setCmiTenTuyen(soapModel.getCmiTenTuyen());
		model.setCmiTrungBinh(soapModel.getCmiTrungBinh());
		model.setCmiTrungMax(soapModel.getCmiTrungMax());
		model.setCmiTrungMin(soapModel.getCmiTrungMin());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<RpDashboardCmi2> toModels(
		RpDashboardCmi2Soap[] soapModels) {

		if (soapModels == null) {
			return null;
		}

		List<RpDashboardCmi2> models = new ArrayList<RpDashboardCmi2>(
			soapModels.length);

		for (RpDashboardCmi2Soap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		drg.moh.service.service.util.ServiceProps.get(
			"lock.expiration.time.drg.moh.service.model.RpDashboardCmi2"));

	public RpDashboardCmi2ModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return RpDashboardCmi2.class;
	}

	@Override
	public String getModelClassName() {
		return RpDashboardCmi2.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<RpDashboardCmi2, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<RpDashboardCmi2, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<RpDashboardCmi2, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((RpDashboardCmi2)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<RpDashboardCmi2, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<RpDashboardCmi2, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(RpDashboardCmi2)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<RpDashboardCmi2, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<RpDashboardCmi2, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, RpDashboardCmi2>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			RpDashboardCmi2.class.getClassLoader(), RpDashboardCmi2.class,
			ModelWrapper.class);

		try {
			Constructor<RpDashboardCmi2> constructor =
				(Constructor<RpDashboardCmi2>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<RpDashboardCmi2, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<RpDashboardCmi2, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<RpDashboardCmi2, Object>>
			attributeGetterFunctions =
				new LinkedHashMap<String, Function<RpDashboardCmi2, Object>>();
		Map<String, BiConsumer<RpDashboardCmi2, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<RpDashboardCmi2, ?>>();

		attributeGetterFunctions.put("id", RpDashboardCmi2::getId);
		attributeSetterBiConsumers.put(
			"id", (BiConsumer<RpDashboardCmi2, Long>)RpDashboardCmi2::setId);
		attributeGetterFunctions.put(
			"cmiTenTuyen", RpDashboardCmi2::getCmiTenTuyen);
		attributeSetterBiConsumers.put(
			"cmiTenTuyen",
			(BiConsumer<RpDashboardCmi2, String>)
				RpDashboardCmi2::setCmiTenTuyen);
		attributeGetterFunctions.put(
			"cmiTrungBinh", RpDashboardCmi2::getCmiTrungBinh);
		attributeSetterBiConsumers.put(
			"cmiTrungBinh",
			(BiConsumer<RpDashboardCmi2, Double>)
				RpDashboardCmi2::setCmiTrungBinh);
		attributeGetterFunctions.put(
			"cmiTrungMax", RpDashboardCmi2::getCmiTrungMax);
		attributeSetterBiConsumers.put(
			"cmiTrungMax",
			(BiConsumer<RpDashboardCmi2, Double>)
				RpDashboardCmi2::setCmiTrungMax);
		attributeGetterFunctions.put(
			"cmiTrungMin", RpDashboardCmi2::getCmiTrungMin);
		attributeSetterBiConsumers.put(
			"cmiTrungMin",
			(BiConsumer<RpDashboardCmi2, Double>)
				RpDashboardCmi2::setCmiTrungMin);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_id = id;
	}

	@JSON
	@Override
	public String getCmiTenTuyen() {
		if (_cmiTenTuyen == null) {
			return "";
		}
		else {
			return _cmiTenTuyen;
		}
	}

	@Override
	public void setCmiTenTuyen(String cmiTenTuyen) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_cmiTenTuyen = cmiTenTuyen;
	}

	@JSON
	@Override
	public double getCmiTrungBinh() {
		return _cmiTrungBinh;
	}

	@Override
	public void setCmiTrungBinh(double cmiTrungBinh) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_cmiTrungBinh = cmiTrungBinh;
	}

	@JSON
	@Override
	public double getCmiTrungMax() {
		return _cmiTrungMax;
	}

	@Override
	public void setCmiTrungMax(double cmiTrungMax) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_cmiTrungMax = cmiTrungMax;
	}

	@JSON
	@Override
	public double getCmiTrungMin() {
		return _cmiTrungMin;
	}

	@Override
	public void setCmiTrungMin(double cmiTrungMin) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_cmiTrungMin = cmiTrungMin;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (entry.getValue() != getColumnValue(entry.getKey())) {
				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, RpDashboardCmi2.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public RpDashboardCmi2 toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, RpDashboardCmi2>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		RpDashboardCmi2Impl rpDashboardCmi2Impl = new RpDashboardCmi2Impl();

		rpDashboardCmi2Impl.setId(getId());
		rpDashboardCmi2Impl.setCmiTenTuyen(getCmiTenTuyen());
		rpDashboardCmi2Impl.setCmiTrungBinh(getCmiTrungBinh());
		rpDashboardCmi2Impl.setCmiTrungMax(getCmiTrungMax());
		rpDashboardCmi2Impl.setCmiTrungMin(getCmiTrungMin());

		rpDashboardCmi2Impl.resetOriginalValues();

		return rpDashboardCmi2Impl;
	}

	@Override
	public int compareTo(RpDashboardCmi2 rpDashboardCmi2) {
		long primaryKey = rpDashboardCmi2.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof RpDashboardCmi2)) {
			return false;
		}

		RpDashboardCmi2 rpDashboardCmi2 = (RpDashboardCmi2)object;

		long primaryKey = rpDashboardCmi2.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<RpDashboardCmi2> toCacheModel() {
		RpDashboardCmi2CacheModel rpDashboardCmi2CacheModel =
			new RpDashboardCmi2CacheModel();

		rpDashboardCmi2CacheModel.id = getId();

		rpDashboardCmi2CacheModel.cmiTenTuyen = getCmiTenTuyen();

		String cmiTenTuyen = rpDashboardCmi2CacheModel.cmiTenTuyen;

		if ((cmiTenTuyen != null) && (cmiTenTuyen.length() == 0)) {
			rpDashboardCmi2CacheModel.cmiTenTuyen = null;
		}

		rpDashboardCmi2CacheModel.cmiTrungBinh = getCmiTrungBinh();

		rpDashboardCmi2CacheModel.cmiTrungMax = getCmiTrungMax();

		rpDashboardCmi2CacheModel.cmiTrungMin = getCmiTrungMin();

		return rpDashboardCmi2CacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<RpDashboardCmi2, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(4 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<RpDashboardCmi2, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<RpDashboardCmi2, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((RpDashboardCmi2)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<RpDashboardCmi2, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<RpDashboardCmi2, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<RpDashboardCmi2, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((RpDashboardCmi2)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, RpDashboardCmi2>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private long _id;
	private String _cmiTenTuyen;
	private double _cmiTrungBinh;
	private double _cmiTrungMax;
	private double _cmiTrungMin;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<RpDashboardCmi2, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((RpDashboardCmi2)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("_id", _id);
		_columnOriginalValues.put("_cmi_tentuyen", _cmiTenTuyen);
		_columnOriginalValues.put("_cmi_trungbinh", _cmiTrungBinh);
		_columnOriginalValues.put("_cmi_max", _cmiTrungMax);
		_columnOriginalValues.put("_cmi_min", _cmiTrungMin);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("_id", "id");
		attributeNames.put("_cmi_tentuyen", "cmiTenTuyen");
		attributeNames.put("_cmi_trungbinh", "cmiTrungBinh");
		attributeNames.put("_cmi_max", "cmiTrungMax");
		attributeNames.put("_cmi_min", "cmiTrungMin");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("_id", 1L);

		columnBitmasks.put("_cmi_tentuyen", 2L);

		columnBitmasks.put("_cmi_trungbinh", 4L);

		columnBitmasks.put("_cmi_max", 8L);

		columnBitmasks.put("_cmi_min", 16L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private RpDashboardCmi2 _escapedModel;

}