/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package drg.moh.service.model.impl;

import drg.moh.service.model.ThongKe;
import drg.moh.service.service.ThongKeLocalServiceUtil;

/**
 * The extended model base implementation for the ThongKe service. Represents a row in the &quot;hsbhyt_tonghop_thongke&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ThongKeImpl}.
 * </p>
 *
 * @author SON
 * @see ThongKeImpl
 * @see ThongKe
 * @generated
 */
public abstract class ThongKeBaseImpl
	extends ThongKeModelImpl implements ThongKe {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a thong ke model instance should use the <code>ThongKe</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			ThongKeLocalServiceUtil.addThongKe(this);
		}
		else {
			ThongKeLocalServiceUtil.updateThongKe(this);
		}
	}

}