/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package drg.moh.service.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import drg.moh.service.model.ThongKe;
import drg.moh.service.model.ThongKeModel;
import drg.moh.service.model.ThongKeSoap;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the ThongKe service. Represents a row in the &quot;hsbhyt_tonghop_thongke&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ThongKeModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ThongKeImpl}.
 * </p>
 *
 * @author SON
 * @see ThongKeImpl
 * @generated
 */
@JSON(strict = true)
public class ThongKeModelImpl
	extends BaseModelImpl<ThongKe> implements ThongKeModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a thong ke model instance should use the <code>ThongKe</code> interface instead.
	 */
	public static final String TABLE_NAME = "hsbhyt_tonghop_thongke";

	public static final Object[][] TABLE_COLUMNS = {
		{"id", Types.BIGINT}, {"ma_cskcb", Types.VARCHAR},
		{"nam_qt", Types.INTEGER}, {"thang_qt", Types.INTEGER},
		{"tong_hoso", Types.BIGINT}, {"t_tongchi", Types.DOUBLE},
		{"t_bhtt", Types.DOUBLE}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("ma_cskcb", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("nam_qt", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("thang_qt", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("tong_hoso", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("t_tongchi", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("t_bhtt", Types.DOUBLE);
	}

	public static final String TABLE_SQL_CREATE =
		"create table hsbhyt_tonghop_thongke (id LONG not null primary key,ma_cskcb VARCHAR(75) null,nam_qt INTEGER,thang_qt INTEGER,tong_hoso LONG,t_tongchi DOUBLE,t_bhtt DOUBLE)";

	public static final String TABLE_SQL_DROP =
		"drop table hsbhyt_tonghop_thongke";

	public static final String ORDER_BY_JPQL = " ORDER BY thongKe.id ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY hsbhyt_tonghop_thongke.id ASC";

	public static final String DATA_SOURCE = "drgDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean ENTITY_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean FINDER_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean COLUMN_BITMASK_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ID_COLUMN_BITMASK = 1L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static ThongKe toModel(ThongKeSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		ThongKe model = new ThongKeImpl();

		model.setId(soapModel.getId());
		model.setMaCoSo(soapModel.getMaCoSo());
		model.setNam(soapModel.getNam());
		model.setThang(soapModel.getThang());
		model.setTongHoSo(soapModel.getTongHoSo());
		model.setTienTongChi(soapModel.getTienTongChi());
		model.setTienBH(soapModel.getTienBH());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<ThongKe> toModels(ThongKeSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<ThongKe> models = new ArrayList<ThongKe>(soapModels.length);

		for (ThongKeSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		drg.moh.service.service.util.ServiceProps.get(
			"lock.expiration.time.drg.moh.service.model.ThongKe"));

	public ThongKeModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ThongKe.class;
	}

	@Override
	public String getModelClassName() {
		return ThongKe.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<ThongKe, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<ThongKe, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ThongKe, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((ThongKe)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<ThongKe, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<ThongKe, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(ThongKe)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<ThongKe, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<ThongKe, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, ThongKe>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			ThongKe.class.getClassLoader(), ThongKe.class, ModelWrapper.class);

		try {
			Constructor<ThongKe> constructor =
				(Constructor<ThongKe>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<ThongKe, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<ThongKe, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<ThongKe, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<ThongKe, Object>>();
		Map<String, BiConsumer<ThongKe, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<ThongKe, ?>>();

		attributeGetterFunctions.put("id", ThongKe::getId);
		attributeSetterBiConsumers.put(
			"id", (BiConsumer<ThongKe, Long>)ThongKe::setId);
		attributeGetterFunctions.put("maCoSo", ThongKe::getMaCoSo);
		attributeSetterBiConsumers.put(
			"maCoSo", (BiConsumer<ThongKe, String>)ThongKe::setMaCoSo);
		attributeGetterFunctions.put("nam", ThongKe::getNam);
		attributeSetterBiConsumers.put(
			"nam", (BiConsumer<ThongKe, Integer>)ThongKe::setNam);
		attributeGetterFunctions.put("thang", ThongKe::getThang);
		attributeSetterBiConsumers.put(
			"thang", (BiConsumer<ThongKe, Integer>)ThongKe::setThang);
		attributeGetterFunctions.put("tongHoSo", ThongKe::getTongHoSo);
		attributeSetterBiConsumers.put(
			"tongHoSo", (BiConsumer<ThongKe, Long>)ThongKe::setTongHoSo);
		attributeGetterFunctions.put("tienTongChi", ThongKe::getTienTongChi);
		attributeSetterBiConsumers.put(
			"tienTongChi",
			(BiConsumer<ThongKe, Double>)ThongKe::setTienTongChi);
		attributeGetterFunctions.put("tienBH", ThongKe::getTienBH);
		attributeSetterBiConsumers.put(
			"tienBH", (BiConsumer<ThongKe, Double>)ThongKe::setTienBH);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_id = id;
	}

	@JSON
	@Override
	public String getMaCoSo() {
		if (_maCoSo == null) {
			return "";
		}
		else {
			return _maCoSo;
		}
	}

	@Override
	public void setMaCoSo(String maCoSo) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_maCoSo = maCoSo;
	}

	@JSON
	@Override
	public int getNam() {
		return _nam;
	}

	@Override
	public void setNam(int nam) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_nam = nam;
	}

	@JSON
	@Override
	public int getThang() {
		return _thang;
	}

	@Override
	public void setThang(int thang) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_thang = thang;
	}

	@JSON
	@Override
	public long getTongHoSo() {
		return _tongHoSo;
	}

	@Override
	public void setTongHoSo(long tongHoSo) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_tongHoSo = tongHoSo;
	}

	@JSON
	@Override
	public double getTienTongChi() {
		return _tienTongChi;
	}

	@Override
	public void setTienTongChi(double tienTongChi) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_tienTongChi = tienTongChi;
	}

	@JSON
	@Override
	public double getTienBH() {
		return _tienBH;
	}

	@Override
	public void setTienBH(double tienBH) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_tienBH = tienBH;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (entry.getValue() != getColumnValue(entry.getKey())) {
				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, ThongKe.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ThongKe toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, ThongKe>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ThongKeImpl thongKeImpl = new ThongKeImpl();

		thongKeImpl.setId(getId());
		thongKeImpl.setMaCoSo(getMaCoSo());
		thongKeImpl.setNam(getNam());
		thongKeImpl.setThang(getThang());
		thongKeImpl.setTongHoSo(getTongHoSo());
		thongKeImpl.setTienTongChi(getTienTongChi());
		thongKeImpl.setTienBH(getTienBH());

		thongKeImpl.resetOriginalValues();

		return thongKeImpl;
	}

	@Override
	public int compareTo(ThongKe thongKe) {
		int value = 0;

		if (getId() < thongKe.getId()) {
			value = -1;
		}
		else if (getId() > thongKe.getId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof ThongKe)) {
			return false;
		}

		ThongKe thongKe = (ThongKe)object;

		long primaryKey = thongKe.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<ThongKe> toCacheModel() {
		ThongKeCacheModel thongKeCacheModel = new ThongKeCacheModel();

		thongKeCacheModel.id = getId();

		thongKeCacheModel.maCoSo = getMaCoSo();

		String maCoSo = thongKeCacheModel.maCoSo;

		if ((maCoSo != null) && (maCoSo.length() == 0)) {
			thongKeCacheModel.maCoSo = null;
		}

		thongKeCacheModel.nam = getNam();

		thongKeCacheModel.thang = getThang();

		thongKeCacheModel.tongHoSo = getTongHoSo();

		thongKeCacheModel.tienTongChi = getTienTongChi();

		thongKeCacheModel.tienBH = getTienBH();

		return thongKeCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<ThongKe, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(4 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<ThongKe, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ThongKe, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((ThongKe)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<ThongKe, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<ThongKe, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ThongKe, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((ThongKe)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, ThongKe>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private long _id;
	private String _maCoSo;
	private int _nam;
	private int _thang;
	private long _tongHoSo;
	private double _tienTongChi;
	private double _tienBH;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<ThongKe, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((ThongKe)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("id", _id);
		_columnOriginalValues.put("ma_cskcb", _maCoSo);
		_columnOriginalValues.put("nam_qt", _nam);
		_columnOriginalValues.put("thang_qt", _thang);
		_columnOriginalValues.put("tong_hoso", _tongHoSo);
		_columnOriginalValues.put("t_tongchi", _tienTongChi);
		_columnOriginalValues.put("t_bhtt", _tienBH);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("ma_cskcb", "maCoSo");
		attributeNames.put("nam_qt", "nam");
		attributeNames.put("thang_qt", "thang");
		attributeNames.put("tong_hoso", "tongHoSo");
		attributeNames.put("t_tongchi", "tienTongChi");
		attributeNames.put("t_bhtt", "tienBH");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("id", 1L);

		columnBitmasks.put("ma_cskcb", 2L);

		columnBitmasks.put("nam_qt", 4L);

		columnBitmasks.put("thang_qt", 8L);

		columnBitmasks.put("tong_hoso", 16L);

		columnBitmasks.put("t_tongchi", 32L);

		columnBitmasks.put("t_bhtt", 64L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private ThongKe _escapedModel;

}