/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package drg.moh.service.model.impl;

import drg.moh.service.model.ViewDanhSachBenhAn;
import drg.moh.service.service.ViewDanhSachBenhAnLocalServiceUtil;

/**
 * The extended model base implementation for the ViewDanhSachBenhAn service. Represents a row in the &quot;view_danhsach_hsba&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ViewDanhSachBenhAnImpl}.
 * </p>
 *
 * @author SON
 * @see ViewDanhSachBenhAnImpl
 * @see ViewDanhSachBenhAn
 * @generated
 */
public abstract class ViewDanhSachBenhAnBaseImpl
	extends ViewDanhSachBenhAnModelImpl implements ViewDanhSachBenhAn {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a view danh sach benh an model instance should use the <code>ViewDanhSachBenhAn</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			ViewDanhSachBenhAnLocalServiceUtil.addViewDanhSachBenhAn(this);
		}
		else {
			ViewDanhSachBenhAnLocalServiceUtil.updateViewDanhSachBenhAn(this);
		}
	}

}