/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package drg.moh.service.service.base;

import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalServiceRegistry;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.service.persistence.ClassNamePersistence;
import com.liferay.portal.kernel.service.persistence.UserPersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;

import drg.moh.service.model.ThongKeBaoCao;
import drg.moh.service.service.ThongKeBaoCaoLocalService;
import drg.moh.service.service.ThongKeBaoCaoLocalServiceUtil;
import drg.moh.service.service.persistence.ThongKeBaoCaoPersistence;
import drg.moh.service.service.persistence.ThongKePersistence;

import java.io.Serializable;

import java.lang.reflect.Field;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the thong ke bao cao local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link drg.moh.service.service.impl.ThongKeBaoCaoLocalServiceImpl}.
 * </p>
 *
 * @author SON
 * @see drg.moh.service.service.impl.ThongKeBaoCaoLocalServiceImpl
 * @generated
 */
public abstract class ThongKeBaoCaoLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements IdentifiableOSGiService, ThongKeBaoCaoLocalService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>ThongKeBaoCaoLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>ThongKeBaoCaoLocalServiceUtil</code>.
	 */

	/**
	 * Adds the thong ke bao cao to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect ThongKeBaoCaoLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param thongKeBaoCao the thong ke bao cao
	 * @return the thong ke bao cao that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public ThongKeBaoCao addThongKeBaoCao(ThongKeBaoCao thongKeBaoCao) {
		thongKeBaoCao.setNew(true);

		return thongKeBaoCaoPersistence.update(thongKeBaoCao);
	}

	/**
	 * Creates a new thong ke bao cao with the primary key. Does not add the thong ke bao cao to the database.
	 *
	 * @param id the primary key for the new thong ke bao cao
	 * @return the new thong ke bao cao
	 */
	@Override
	@Transactional(enabled = false)
	public ThongKeBaoCao createThongKeBaoCao(long id) {
		return thongKeBaoCaoPersistence.create(id);
	}

	/**
	 * Deletes the thong ke bao cao with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect ThongKeBaoCaoLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param id the primary key of the thong ke bao cao
	 * @return the thong ke bao cao that was removed
	 * @throws PortalException if a thong ke bao cao with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public ThongKeBaoCao deleteThongKeBaoCao(long id) throws PortalException {
		return thongKeBaoCaoPersistence.remove(id);
	}

	/**
	 * Deletes the thong ke bao cao from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect ThongKeBaoCaoLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param thongKeBaoCao the thong ke bao cao
	 * @return the thong ke bao cao that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public ThongKeBaoCao deleteThongKeBaoCao(ThongKeBaoCao thongKeBaoCao) {
		return thongKeBaoCaoPersistence.remove(thongKeBaoCao);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return thongKeBaoCaoPersistence.dslQuery(dslQuery);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			ThongKeBaoCao.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return thongKeBaoCaoPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>drg.moh.service.model.impl.ThongKeBaoCaoModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return thongKeBaoCaoPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>drg.moh.service.model.impl.ThongKeBaoCaoModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return thongKeBaoCaoPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return thongKeBaoCaoPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return thongKeBaoCaoPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public ThongKeBaoCao fetchThongKeBaoCao(long id) {
		return thongKeBaoCaoPersistence.fetchByPrimaryKey(id);
	}

	/**
	 * Returns the thong ke bao cao with the primary key.
	 *
	 * @param id the primary key of the thong ke bao cao
	 * @return the thong ke bao cao
	 * @throws PortalException if a thong ke bao cao with the primary key could not be found
	 */
	@Override
	public ThongKeBaoCao getThongKeBaoCao(long id) throws PortalException {
		return thongKeBaoCaoPersistence.findByPrimaryKey(id);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(thongKeBaoCaoLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(ThongKeBaoCao.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("id");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			thongKeBaoCaoLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(ThongKeBaoCao.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName("id");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(thongKeBaoCaoLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(ThongKeBaoCao.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("id");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return thongKeBaoCaoPersistence.create(
			((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return thongKeBaoCaoLocalService.deleteThongKeBaoCao(
			(ThongKeBaoCao)persistedModel);
	}

	@Override
	public BasePersistence<ThongKeBaoCao> getBasePersistence() {
		return thongKeBaoCaoPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return thongKeBaoCaoPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the thong ke bao caos.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>drg.moh.service.model.impl.ThongKeBaoCaoModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of thong ke bao caos
	 * @param end the upper bound of the range of thong ke bao caos (not inclusive)
	 * @return the range of thong ke bao caos
	 */
	@Override
	public List<ThongKeBaoCao> getThongKeBaoCaos(int start, int end) {
		return thongKeBaoCaoPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of thong ke bao caos.
	 *
	 * @return the number of thong ke bao caos
	 */
	@Override
	public int getThongKeBaoCaosCount() {
		return thongKeBaoCaoPersistence.countAll();
	}

	/**
	 * Updates the thong ke bao cao in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect ThongKeBaoCaoLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param thongKeBaoCao the thong ke bao cao
	 * @return the thong ke bao cao that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public ThongKeBaoCao updateThongKeBaoCao(ThongKeBaoCao thongKeBaoCao) {
		return thongKeBaoCaoPersistence.update(thongKeBaoCao);
	}

	/**
	 * Returns the thong ke local service.
	 *
	 * @return the thong ke local service
	 */
	public drg.moh.service.service.ThongKeLocalService
		getThongKeLocalService() {

		return thongKeLocalService;
	}

	/**
	 * Sets the thong ke local service.
	 *
	 * @param thongKeLocalService the thong ke local service
	 */
	public void setThongKeLocalService(
		drg.moh.service.service.ThongKeLocalService thongKeLocalService) {

		this.thongKeLocalService = thongKeLocalService;
	}

	/**
	 * Returns the thong ke persistence.
	 *
	 * @return the thong ke persistence
	 */
	public ThongKePersistence getThongKePersistence() {
		return thongKePersistence;
	}

	/**
	 * Sets the thong ke persistence.
	 *
	 * @param thongKePersistence the thong ke persistence
	 */
	public void setThongKePersistence(ThongKePersistence thongKePersistence) {
		this.thongKePersistence = thongKePersistence;
	}

	/**
	 * Returns the thong ke bao cao local service.
	 *
	 * @return the thong ke bao cao local service
	 */
	public ThongKeBaoCaoLocalService getThongKeBaoCaoLocalService() {
		return thongKeBaoCaoLocalService;
	}

	/**
	 * Sets the thong ke bao cao local service.
	 *
	 * @param thongKeBaoCaoLocalService the thong ke bao cao local service
	 */
	public void setThongKeBaoCaoLocalService(
		ThongKeBaoCaoLocalService thongKeBaoCaoLocalService) {

		this.thongKeBaoCaoLocalService = thongKeBaoCaoLocalService;
	}

	/**
	 * Returns the thong ke bao cao persistence.
	 *
	 * @return the thong ke bao cao persistence
	 */
	public ThongKeBaoCaoPersistence getThongKeBaoCaoPersistence() {
		return thongKeBaoCaoPersistence;
	}

	/**
	 * Sets the thong ke bao cao persistence.
	 *
	 * @param thongKeBaoCaoPersistence the thong ke bao cao persistence
	 */
	public void setThongKeBaoCaoPersistence(
		ThongKeBaoCaoPersistence thongKeBaoCaoPersistence) {

		this.thongKeBaoCaoPersistence = thongKeBaoCaoPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService
		getCounterLocalService() {

		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService
			counterLocalService) {

		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the class name local service.
	 *
	 * @return the class name local service
	 */
	public com.liferay.portal.kernel.service.ClassNameLocalService
		getClassNameLocalService() {

		return classNameLocalService;
	}

	/**
	 * Sets the class name local service.
	 *
	 * @param classNameLocalService the class name local service
	 */
	public void setClassNameLocalService(
		com.liferay.portal.kernel.service.ClassNameLocalService
			classNameLocalService) {

		this.classNameLocalService = classNameLocalService;
	}

	/**
	 * Returns the class name persistence.
	 *
	 * @return the class name persistence
	 */
	public ClassNamePersistence getClassNamePersistence() {
		return classNamePersistence;
	}

	/**
	 * Sets the class name persistence.
	 *
	 * @param classNamePersistence the class name persistence
	 */
	public void setClassNamePersistence(
		ClassNamePersistence classNamePersistence) {

		this.classNamePersistence = classNamePersistence;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.kernel.service.ResourceLocalService
		getResourceLocalService() {

		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.kernel.service.ResourceLocalService
			resourceLocalService) {

		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.kernel.service.UserLocalService
		getUserLocalService() {

		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.kernel.service.UserLocalService userLocalService) {

		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		persistedModelLocalServiceRegistry.register(
			"drg.moh.service.model.ThongKeBaoCao", thongKeBaoCaoLocalService);

		_setLocalServiceUtilService(thongKeBaoCaoLocalService);
	}

	public void destroy() {
		persistedModelLocalServiceRegistry.unregister(
			"drg.moh.service.model.ThongKeBaoCao");

		_setLocalServiceUtilService(null);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return ThongKeBaoCaoLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return ThongKeBaoCao.class;
	}

	protected String getModelClassName() {
		return ThongKeBaoCao.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = thongKeBaoCaoPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	private void _setLocalServiceUtilService(
		ThongKeBaoCaoLocalService thongKeBaoCaoLocalService) {

		try {
			Field field = ThongKeBaoCaoLocalServiceUtil.class.getDeclaredField(
				"_service");

			field.setAccessible(true);

			field.set(null, thongKeBaoCaoLocalService);
		}
		catch (ReflectiveOperationException reflectiveOperationException) {
			throw new RuntimeException(reflectiveOperationException);
		}
	}

	@BeanReference(type = drg.moh.service.service.ThongKeLocalService.class)
	protected drg.moh.service.service.ThongKeLocalService thongKeLocalService;

	@BeanReference(type = ThongKePersistence.class)
	protected ThongKePersistence thongKePersistence;

	@BeanReference(type = ThongKeBaoCaoLocalService.class)
	protected ThongKeBaoCaoLocalService thongKeBaoCaoLocalService;

	@BeanReference(type = ThongKeBaoCaoPersistence.class)
	protected ThongKeBaoCaoPersistence thongKeBaoCaoPersistence;

	@ServiceReference(
		type = com.liferay.counter.kernel.service.CounterLocalService.class
	)
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@ServiceReference(
		type = com.liferay.portal.kernel.service.ClassNameLocalService.class
	)
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@ServiceReference(type = ClassNamePersistence.class)
	protected ClassNamePersistence classNamePersistence;

	@ServiceReference(
		type = com.liferay.portal.kernel.service.ResourceLocalService.class
	)
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@ServiceReference(
		type = com.liferay.portal.kernel.service.UserLocalService.class
	)
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	@ServiceReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;

	@ServiceReference(type = PersistedModelLocalServiceRegistry.class)
	protected PersistedModelLocalServiceRegistry
		persistedModelLocalServiceRegistry;

}